// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/msg.proto

package protomsg

/*
包名，通过protoc生成时go文件时
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 手机类型
// 枚举类型第一个字段必须为0
type PhoneType int32

const (
	PhoneType_HOME PhoneType = 0
	PhoneType_WORK PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
}

var PhoneType_value = map[string]int32{
	"HOME": 0,
	"WORK": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{0}
}

type MsgBase struct {
	ModeType             string   `protobuf:"bytes,1,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	MsgType              string   `protobuf:"bytes,3,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	ConnectId            int32    `protobuf:"varint,4,opt,name=ConnectId,proto3" json:"ConnectId,omitempty"`
	Datas                []byte   `protobuf:"bytes,5,opt,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBase) Reset()         { *m = MsgBase{} }
func (m *MsgBase) String() string { return proto.CompactTextString(m) }
func (*MsgBase) ProtoMessage()    {}
func (*MsgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{0}
}
func (m *MsgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBase.Unmarshal(m, b)
}
func (m *MsgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBase.Marshal(b, m, deterministic)
}
func (dst *MsgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBase.Merge(dst, src)
}
func (m *MsgBase) XXX_Size() int {
	return xxx_messageInfo_MsgBase.Size(m)
}
func (m *MsgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBase proto.InternalMessageInfo

func (m *MsgBase) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

func (m *MsgBase) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgBase) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MsgBase) GetConnectId() int32 {
	if m != nil {
		return m.ConnectId
	}
	return 0
}

func (m *MsgBase) GetDatas() []byte {
	if m != nil {
		return m.Datas
	}
	return nil
}

type MsgRegisterToGate struct {
	ModeType             string   `protobuf:"bytes,1,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterToGate) Reset()         { *m = MsgRegisterToGate{} }
func (m *MsgRegisterToGate) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterToGate) ProtoMessage()    {}
func (*MsgRegisterToGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{1}
}
func (m *MsgRegisterToGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterToGate.Unmarshal(m, b)
}
func (m *MsgRegisterToGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterToGate.Marshal(b, m, deterministic)
}
func (dst *MsgRegisterToGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterToGate.Merge(dst, src)
}
func (m *MsgRegisterToGate) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterToGate.Size(m)
}
func (m *MsgRegisterToGate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterToGate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterToGate proto.InternalMessageInfo

func (m *MsgRegisterToGate) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

type CS_MsgQuickLogin struct {
	Platform             string   `protobuf:"bytes,1,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Machineid            string   `protobuf:"bytes,2,opt,name=Machineid,proto3" json:"Machineid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_MsgQuickLogin) Reset()         { *m = CS_MsgQuickLogin{} }
func (m *CS_MsgQuickLogin) String() string { return proto.CompactTextString(m) }
func (*CS_MsgQuickLogin) ProtoMessage()    {}
func (*CS_MsgQuickLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{2}
}
func (m *CS_MsgQuickLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_MsgQuickLogin.Unmarshal(m, b)
}
func (m *CS_MsgQuickLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_MsgQuickLogin.Marshal(b, m, deterministic)
}
func (dst *CS_MsgQuickLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_MsgQuickLogin.Merge(dst, src)
}
func (m *CS_MsgQuickLogin) XXX_Size() int {
	return xxx_messageInfo_CS_MsgQuickLogin.Size(m)
}
func (m *CS_MsgQuickLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_MsgQuickLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CS_MsgQuickLogin proto.InternalMessageInfo

func (m *CS_MsgQuickLogin) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CS_MsgQuickLogin) GetMachineid() string {
	if m != nil {
		return m.Machineid
	}
	return ""
}

func (m *CS_MsgQuickLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CS_Login struct {
	Phonenumber          string   `protobuf:"bytes,1,opt,name=Phonenumber,proto3" json:"Phonenumber,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Machineid            string   `protobuf:"bytes,3,opt,name=Machineid,proto3" json:"Machineid,omitempty"`
	WechatId             string   `protobuf:"bytes,4,opt,name=Wechat_id,json=WechatId,proto3" json:"Wechat_id,omitempty"`
	QQId                 string   `protobuf:"bytes,5,opt,name=QQ_id,json=QQId,proto3" json:"QQ_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Login) Reset()         { *m = CS_Login{} }
func (m *CS_Login) String() string { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()    {}
func (*CS_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{3}
}
func (m *CS_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Login.Unmarshal(m, b)
}
func (m *CS_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Login.Marshal(b, m, deterministic)
}
func (dst *CS_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Login.Merge(dst, src)
}
func (m *CS_Login) XXX_Size() int {
	return xxx_messageInfo_CS_Login.Size(m)
}
func (m *CS_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Login.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Login proto.InternalMessageInfo

func (m *CS_Login) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *CS_Login) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CS_Login) GetMachineid() string {
	if m != nil {
		return m.Machineid
	}
	return ""
}

func (m *CS_Login) GetWechatId() string {
	if m != nil {
		return m.WechatId
	}
	return ""
}

func (m *CS_Login) GetQQId() string {
	if m != nil {
		return m.QQId
	}
	return ""
}

type Point struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{4}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// 测试
type CS_SetTarget struct {
	TargetPos            *Point   `protobuf:"bytes,1,opt,name=TargetPos,proto3" json:"TargetPos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_SetTarget) Reset()         { *m = CS_SetTarget{} }
func (m *CS_SetTarget) String() string { return proto.CompactTextString(m) }
func (*CS_SetTarget) ProtoMessage()    {}
func (*CS_SetTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{5}
}
func (m *CS_SetTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_SetTarget.Unmarshal(m, b)
}
func (m *CS_SetTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_SetTarget.Marshal(b, m, deterministic)
}
func (dst *CS_SetTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_SetTarget.Merge(dst, src)
}
func (m *CS_SetTarget) XXX_Size() int {
	return xxx_messageInfo_CS_SetTarget.Size(m)
}
func (m *CS_SetTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_SetTarget.DiscardUnknown(m)
}

var xxx_messageInfo_CS_SetTarget proto.InternalMessageInfo

func (m *CS_SetTarget) GetTargetPos() *Point {
	if m != nil {
		return m.TargetPos
	}
	return nil
}

type MsgUserEnterScene struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ConnectId            int32    `protobuf:"varint,2,opt,name=ConnectId,proto3" json:"ConnectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUserEnterScene) Reset()         { *m = MsgUserEnterScene{} }
func (m *MsgUserEnterScene) String() string { return proto.CompactTextString(m) }
func (*MsgUserEnterScene) ProtoMessage()    {}
func (*MsgUserEnterScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{6}
}
func (m *MsgUserEnterScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUserEnterScene.Unmarshal(m, b)
}
func (m *MsgUserEnterScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUserEnterScene.Marshal(b, m, deterministic)
}
func (dst *MsgUserEnterScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUserEnterScene.Merge(dst, src)
}
func (m *MsgUserEnterScene) XXX_Size() int {
	return xxx_messageInfo_MsgUserEnterScene.Size(m)
}
func (m *MsgUserEnterScene) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUserEnterScene.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUserEnterScene proto.InternalMessageInfo

func (m *MsgUserEnterScene) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgUserEnterScene) GetConnectId() int32 {
	if m != nil {
		return m.ConnectId
	}
	return 0
}

// ------服务器发给客户端的消息
// 测试
type SC_LogicFrame struct {
	Position             *Point   `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_LogicFrame) Reset()         { *m = SC_LogicFrame{} }
func (m *SC_LogicFrame) String() string { return proto.CompactTextString(m) }
func (*SC_LogicFrame) ProtoMessage()    {}
func (*SC_LogicFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{7}
}
func (m *SC_LogicFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_LogicFrame.Unmarshal(m, b)
}
func (m *SC_LogicFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_LogicFrame.Marshal(b, m, deterministic)
}
func (dst *SC_LogicFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_LogicFrame.Merge(dst, src)
}
func (m *SC_LogicFrame) XXX_Size() int {
	return xxx_messageInfo_SC_LogicFrame.Size(m)
}
func (m *SC_LogicFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_LogicFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SC_LogicFrame proto.InternalMessageInfo

func (m *SC_LogicFrame) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

type SC_Logined struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Logined) Reset()         { *m = SC_Logined{} }
func (m *SC_Logined) String() string { return proto.CompactTextString(m) }
func (*SC_Logined) ProtoMessage()    {}
func (*SC_Logined) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{8}
}
func (m *SC_Logined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Logined.Unmarshal(m, b)
}
func (m *SC_Logined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Logined.Marshal(b, m, deterministic)
}
func (dst *SC_Logined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Logined.Merge(dst, src)
}
func (m *SC_Logined) XXX_Size() int {
	return xxx_messageInfo_SC_Logined.Size(m)
}
func (m *SC_Logined) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Logined.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Logined proto.InternalMessageInfo

func (m *SC_Logined) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SC_Logined) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBase)(nil), "protomsg.MsgBase")
	proto.RegisterType((*MsgRegisterToGate)(nil), "protomsg.MsgRegisterToGate")
	proto.RegisterType((*CS_MsgQuickLogin)(nil), "protomsg.CS_MsgQuickLogin")
	proto.RegisterType((*CS_Login)(nil), "protomsg.CS_Login")
	proto.RegisterType((*Point)(nil), "protomsg.Point")
	proto.RegisterType((*CS_SetTarget)(nil), "protomsg.CS_SetTarget")
	proto.RegisterType((*MsgUserEnterScene)(nil), "protomsg.MsgUserEnterScene")
	proto.RegisterType((*SC_LogicFrame)(nil), "protomsg.SC_LogicFrame")
	proto.RegisterType((*SC_Logined)(nil), "protomsg.SC_Logined")
	proto.RegisterEnum("protomsg.PhoneType", PhoneType_name, PhoneType_value)
}

func init() { proto.RegisterFile("protobuf/msg.proto", fileDescriptor_617aaba9bf0c07c7) }

var fileDescriptor_617aaba9bf0c07c7 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x65, 0x9d, 0x18, 0xec, 0x69, 0x10, 0x61, 0xe1, 0x60, 0x01, 0x12, 0x91, 0xb9, 0x44, 0x20,
	0x52, 0x09, 0x24, 0x4e, 0x70, 0xc1, 0x04, 0x88, 0xc0, 0xd4, 0x5e, 0xa7, 0x6a, 0x7b, 0x0a, 0x1b,
	0x7b, 0xeb, 0x58, 0xe0, 0xdd, 0x6a, 0x77, 0x73, 0xe0, 0x03, 0xf8, 0x07, 0x3e, 0x17, 0x79, 0x6c,
	0x27, 0xb4, 0x12, 0x39, 0x79, 0xde, 0xf8, 0xcd, 0xbc, 0xd9, 0x99, 0x07, 0xf4, 0x4a, 0x2b, 0xab,
	0xd6, 0xdb, 0xcb, 0xe3, 0xda, 0x94, 0x33, 0x04, 0xd4, 0xc3, 0x4f, 0x6d, 0xca, 0xf0, 0x37, 0x81,
	0x3b, 0xb1, 0x29, 0xdf, 0x73, 0x23, 0xe8, 0x23, 0xf0, 0x62, 0x55, 0x88, 0xe5, 0xaf, 0x2b, 0x11,
	0x90, 0x09, 0x99, 0xfa, 0x6c, 0x87, 0xe9, 0x18, 0x06, 0xa7, 0x55, 0x11, 0x38, 0x13, 0x32, 0x75,
	0x59, 0x13, 0xd2, 0x00, 0x0b, 0x91, 0x3c, 0x40, 0x72, 0x0f, 0xe9, 0x13, 0xf0, 0x23, 0x25, 0xa5,
	0xc8, 0xed, 0xa2, 0x08, 0x86, 0x58, 0xb1, 0x4f, 0xd0, 0x87, 0xe0, 0x7e, 0xe0, 0x96, 0x9b, 0xc0,
	0x9d, 0x90, 0xe9, 0x88, 0xb5, 0x20, 0x3c, 0x86, 0xfb, 0xb1, 0x29, 0x99, 0x28, 0x2b, 0x63, 0x85,
	0x5e, 0xaa, 0x4f, 0xdc, 0x1e, 0x1c, 0x28, 0xfc, 0x0e, 0xe3, 0x28, 0x5b, 0xc5, 0xa6, 0x4c, 0xb7,
	0x55, 0xfe, 0xe3, 0xab, 0x2a, 0x2b, 0xd9, 0xf0, 0x93, 0x9f, 0xdc, 0x5e, 0x2a, 0x5d, 0xf7, 0xfc,
	0x1e, 0x37, 0x43, 0xc5, 0x3c, 0xdf, 0x54, 0x52, 0x74, 0xcf, 0xf0, 0xd9, 0x3e, 0x41, 0x29, 0x0c,
	0xbf, 0xf1, 0xba, 0x7f, 0x09, 0xc6, 0xe1, 0x1f, 0x02, 0x5e, 0x94, 0xad, 0xda, 0xd6, 0x13, 0x38,
	0x4a, 0x36, 0x4a, 0x0a, 0xb9, 0xad, 0xd7, 0x42, 0x77, 0xdd, 0xff, 0x4d, 0x5d, 0x13, 0x77, 0x0e,
	0x89, 0x0f, 0x6e, 0x8a, 0x3f, 0x06, 0xff, 0x4c, 0xe4, 0x1b, 0x6e, 0x57, 0x55, 0xbb, 0x2f, 0x9f,
	0x79, 0x6d, 0x62, 0x51, 0xd0, 0x07, 0xe0, 0xa6, 0x69, 0xf3, 0xc3, 0x6d, 0x47, 0x4b, 0xd3, 0x45,
	0x11, 0x3e, 0x03, 0x37, 0x51, 0x95, 0xb4, 0x74, 0x04, 0xe4, 0x1c, 0x87, 0x71, 0x18, 0x39, 0x6f,
	0xd0, 0x05, 0x6a, 0x3b, 0x8c, 0x5c, 0x84, 0xef, 0x60, 0x14, 0x65, 0xab, 0x4c, 0xd8, 0x25, 0xd7,
	0xa5, 0xb0, 0xf4, 0x25, 0xf8, 0x6d, 0x94, 0x28, 0x83, 0x35, 0x47, 0xaf, 0xee, 0xcd, 0x7a, 0x23,
	0xcc, 0xb0, 0x1f, 0xdb, 0x33, 0xc2, 0x08, 0x2f, 0x72, 0x6a, 0x84, 0x9e, 0x4b, 0x2b, 0x74, 0x96,
	0x0b, 0xb9, 0xb3, 0x01, 0xd9, 0xdb, 0xe0, 0xda, 0xb1, 0x9d, 0x1b, 0xc7, 0x0e, 0xdf, 0xc2, 0xdd,
	0x2c, 0xc2, 0x15, 0xe6, 0x1f, 0x35, 0xaf, 0x05, 0x7d, 0x01, 0x5e, 0xa2, 0x4c, 0x65, 0x2b, 0x25,
	0xff, 0x37, 0xc3, 0x8e, 0x10, 0xbe, 0x01, 0xe8, 0xaa, 0xa5, 0xc0, 0x1b, 0x45, 0xaa, 0x10, 0x9d,
	0x38, 0xc6, 0x8d, 0x99, 0xe6, 0x5a, 0x2b, 0xdd, 0x6d, 0xbc, 0x05, 0xcf, 0x9f, 0x82, 0x8f, 0x97,
	0x41, 0x37, 0x7a, 0x30, 0xfc, 0x7c, 0x12, 0xcf, 0xc7, 0xb7, 0x9a, 0xe8, 0xec, 0x84, 0x7d, 0x19,
	0x93, 0xf5, 0x6d, 0x94, 0x7c, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xe1, 0xb9, 0x27, 0x1c,
	0x03, 0x00, 0x00,
}
