// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/msg.proto

package protomsg

/*
包名，通过protoc生成时go文件时
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgBase struct {
	ModeType             string   `protobuf:"bytes,1,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	MsgType              string   `protobuf:"bytes,3,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	ConnectId            int32    `protobuf:"varint,4,opt,name=ConnectId,proto3" json:"ConnectId,omitempty"`
	Datas                []byte   `protobuf:"bytes,5,opt,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBase) Reset()         { *m = MsgBase{} }
func (m *MsgBase) String() string { return proto.CompactTextString(m) }
func (*MsgBase) ProtoMessage()    {}
func (*MsgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{0}
}
func (m *MsgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBase.Unmarshal(m, b)
}
func (m *MsgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBase.Marshal(b, m, deterministic)
}
func (dst *MsgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBase.Merge(dst, src)
}
func (m *MsgBase) XXX_Size() int {
	return xxx_messageInfo_MsgBase.Size(m)
}
func (m *MsgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBase proto.InternalMessageInfo

func (m *MsgBase) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

func (m *MsgBase) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgBase) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MsgBase) GetConnectId() int32 {
	if m != nil {
		return m.ConnectId
	}
	return 0
}

func (m *MsgBase) GetDatas() []byte {
	if m != nil {
		return m.Datas
	}
	return nil
}

type MsgRegisterToGate struct {
	ModeType             string   `protobuf:"bytes,1,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterToGate) Reset()         { *m = MsgRegisterToGate{} }
func (m *MsgRegisterToGate) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterToGate) ProtoMessage()    {}
func (*MsgRegisterToGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{1}
}
func (m *MsgRegisterToGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterToGate.Unmarshal(m, b)
}
func (m *MsgRegisterToGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterToGate.Marshal(b, m, deterministic)
}
func (dst *MsgRegisterToGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterToGate.Merge(dst, src)
}
func (m *MsgRegisterToGate) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterToGate.Size(m)
}
func (m *MsgRegisterToGate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterToGate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterToGate proto.InternalMessageInfo

func (m *MsgRegisterToGate) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

type CS_MsgQuickLogin struct {
	Platform             string   `protobuf:"bytes,1,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Machineid            string   `protobuf:"bytes,2,opt,name=Machineid,proto3" json:"Machineid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_MsgQuickLogin) Reset()         { *m = CS_MsgQuickLogin{} }
func (m *CS_MsgQuickLogin) String() string { return proto.CompactTextString(m) }
func (*CS_MsgQuickLogin) ProtoMessage()    {}
func (*CS_MsgQuickLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{2}
}
func (m *CS_MsgQuickLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_MsgQuickLogin.Unmarshal(m, b)
}
func (m *CS_MsgQuickLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_MsgQuickLogin.Marshal(b, m, deterministic)
}
func (dst *CS_MsgQuickLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_MsgQuickLogin.Merge(dst, src)
}
func (m *CS_MsgQuickLogin) XXX_Size() int {
	return xxx_messageInfo_CS_MsgQuickLogin.Size(m)
}
func (m *CS_MsgQuickLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_MsgQuickLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CS_MsgQuickLogin proto.InternalMessageInfo

func (m *CS_MsgQuickLogin) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CS_MsgQuickLogin) GetMachineid() string {
	if m != nil {
		return m.Machineid
	}
	return ""
}

func (m *CS_MsgQuickLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CS_Login struct {
	Phonenumber          string   `protobuf:"bytes,1,opt,name=Phonenumber,proto3" json:"Phonenumber,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Machineid            string   `protobuf:"bytes,3,opt,name=Machineid,proto3" json:"Machineid,omitempty"`
	WechatId             string   `protobuf:"bytes,4,opt,name=Wechat_id,json=WechatId,proto3" json:"Wechat_id,omitempty"`
	QQId                 string   `protobuf:"bytes,5,opt,name=QQ_id,json=QQId,proto3" json:"QQ_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Login) Reset()         { *m = CS_Login{} }
func (m *CS_Login) String() string { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()    {}
func (*CS_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{3}
}
func (m *CS_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Login.Unmarshal(m, b)
}
func (m *CS_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Login.Marshal(b, m, deterministic)
}
func (dst *CS_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Login.Merge(dst, src)
}
func (m *CS_Login) XXX_Size() int {
	return xxx_messageInfo_CS_Login.Size(m)
}
func (m *CS_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Login.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Login proto.InternalMessageInfo

func (m *CS_Login) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *CS_Login) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CS_Login) GetMachineid() string {
	if m != nil {
		return m.Machineid
	}
	return ""
}

func (m *CS_Login) GetWechatId() string {
	if m != nil {
		return m.WechatId
	}
	return ""
}

func (m *CS_Login) GetQQId() string {
	if m != nil {
		return m.QQId
	}
	return ""
}

// 登录成功后的 选择角色
type CS_SelectCharacter struct {
	SelectCharacter      *CharacterBaseDatas `protobuf:"bytes,1,opt,name=SelectCharacter,proto3" json:"SelectCharacter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CS_SelectCharacter) Reset()         { *m = CS_SelectCharacter{} }
func (m *CS_SelectCharacter) String() string { return proto.CompactTextString(m) }
func (*CS_SelectCharacter) ProtoMessage()    {}
func (*CS_SelectCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{4}
}
func (m *CS_SelectCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_SelectCharacter.Unmarshal(m, b)
}
func (m *CS_SelectCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_SelectCharacter.Marshal(b, m, deterministic)
}
func (dst *CS_SelectCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_SelectCharacter.Merge(dst, src)
}
func (m *CS_SelectCharacter) XXX_Size() int {
	return xxx_messageInfo_CS_SelectCharacter.Size(m)
}
func (m *CS_SelectCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_SelectCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_CS_SelectCharacter proto.InternalMessageInfo

func (m *CS_SelectCharacter) GetSelectCharacter() *CharacterBaseDatas {
	if m != nil {
		return m.SelectCharacter
	}
	return nil
}

// loading界面加载完成
type CS_LodingScene struct {
	SceneID              int32    `protobuf:"varint,1,opt,name=SceneID,proto3" json:"SceneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_LodingScene) Reset()         { *m = CS_LodingScene{} }
func (m *CS_LodingScene) String() string { return proto.CompactTextString(m) }
func (*CS_LodingScene) ProtoMessage()    {}
func (*CS_LodingScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{5}
}
func (m *CS_LodingScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_LodingScene.Unmarshal(m, b)
}
func (m *CS_LodingScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_LodingScene.Marshal(b, m, deterministic)
}
func (dst *CS_LodingScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_LodingScene.Merge(dst, src)
}
func (m *CS_LodingScene) XXX_Size() int {
	return xxx_messageInfo_CS_LodingScene.Size(m)
}
func (m *CS_LodingScene) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_LodingScene.DiscardUnknown(m)
}

var xxx_messageInfo_CS_LodingScene proto.InternalMessageInfo

func (m *CS_LodingScene) GetSceneID() int32 {
	if m != nil {
		return m.SceneID
	}
	return 0
}

// 装备栏
type UnitEquip struct {
	Pos                  int32    `protobuf:"varint,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	TypdID               int32    `protobuf:"varint,2,opt,name=TypdID,proto3" json:"TypdID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitEquip) Reset()         { *m = UnitEquip{} }
func (m *UnitEquip) String() string { return proto.CompactTextString(m) }
func (*UnitEquip) ProtoMessage()    {}
func (*UnitEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{6}
}
func (m *UnitEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitEquip.Unmarshal(m, b)
}
func (m *UnitEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitEquip.Marshal(b, m, deterministic)
}
func (dst *UnitEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitEquip.Merge(dst, src)
}
func (m *UnitEquip) XXX_Size() int {
	return xxx_messageInfo_UnitEquip.Size(m)
}
func (m *UnitEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitEquip.DiscardUnknown(m)
}

var xxx_messageInfo_UnitEquip proto.InternalMessageInfo

func (m *UnitEquip) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *UnitEquip) GetTypdID() int32 {
	if m != nil {
		return m.TypdID
	}
	return 0
}

// 单位面板详细信息
type UnitBoardDatas struct {
	ID                    int32        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                  string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	AttributeStrength     float32      `protobuf:"fixed32,3,opt,name=AttributeStrength,proto3" json:"AttributeStrength,omitempty"`
	AttributeAgility      float32      `protobuf:"fixed32,4,opt,name=AttributeAgility,proto3" json:"AttributeAgility,omitempty"`
	AttributeIntelligence float32      `protobuf:"fixed32,5,opt,name=AttributeIntelligence,proto3" json:"AttributeIntelligence,omitempty"`
	Attack                int32        `protobuf:"varint,6,opt,name=Attack,proto3" json:"Attack,omitempty"`
	AttackSpeed           float32      `protobuf:"fixed32,7,opt,name=AttackSpeed,proto3" json:"AttackSpeed,omitempty"`
	AttackRange           float32      `protobuf:"fixed32,8,opt,name=AttackRange,proto3" json:"AttackRange,omitempty"`
	MoveSpeed             float32      `protobuf:"fixed32,9,opt,name=MoveSpeed,proto3" json:"MoveSpeed,omitempty"`
	MagicScale            float32      `protobuf:"fixed32,10,opt,name=MagicScale,proto3" json:"MagicScale,omitempty"`
	MPRegain              float32      `protobuf:"fixed32,11,opt,name=MPRegain,proto3" json:"MPRegain,omitempty"`
	PhysicalAmaor         float32      `protobuf:"fixed32,12,opt,name=PhysicalAmaor,proto3" json:"PhysicalAmaor,omitempty"`
	PhysicalResist        float32      `protobuf:"fixed32,13,opt,name=PhysicalResist,proto3" json:"PhysicalResist,omitempty"`
	MagicAmaor            float32      `protobuf:"fixed32,14,opt,name=MagicAmaor,proto3" json:"MagicAmaor,omitempty"`
	StatusAmaor           float32      `protobuf:"fixed32,15,opt,name=StatusAmaor,proto3" json:"StatusAmaor,omitempty"`
	Dodge                 float32      `protobuf:"fixed32,16,opt,name=Dodge,proto3" json:"Dodge,omitempty"`
	HPRegain              float32      `protobuf:"fixed32,17,opt,name=HPRegain,proto3" json:"HPRegain,omitempty"`
	AttributePrimary      int32        `protobuf:"varint,18,opt,name=AttributePrimary,proto3" json:"AttributePrimary,omitempty"`
	DropItems             string       `protobuf:"bytes,19,opt,name=DropItems,proto3" json:"DropItems,omitempty"`
	RemainExperience      int32        `protobuf:"varint,20,opt,name=RemainExperience,proto3" json:"RemainExperience,omitempty"`
	Equips                []*UnitEquip `protobuf:"bytes,21,rep,name=Equips,proto3" json:"Equips,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *UnitBoardDatas) Reset()         { *m = UnitBoardDatas{} }
func (m *UnitBoardDatas) String() string { return proto.CompactTextString(m) }
func (*UnitBoardDatas) ProtoMessage()    {}
func (*UnitBoardDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{7}
}
func (m *UnitBoardDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitBoardDatas.Unmarshal(m, b)
}
func (m *UnitBoardDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitBoardDatas.Marshal(b, m, deterministic)
}
func (dst *UnitBoardDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitBoardDatas.Merge(dst, src)
}
func (m *UnitBoardDatas) XXX_Size() int {
	return xxx_messageInfo_UnitBoardDatas.Size(m)
}
func (m *UnitBoardDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitBoardDatas.DiscardUnknown(m)
}

var xxx_messageInfo_UnitBoardDatas proto.InternalMessageInfo

func (m *UnitBoardDatas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UnitBoardDatas) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitBoardDatas) GetAttributeStrength() float32 {
	if m != nil {
		return m.AttributeStrength
	}
	return 0
}

func (m *UnitBoardDatas) GetAttributeAgility() float32 {
	if m != nil {
		return m.AttributeAgility
	}
	return 0
}

func (m *UnitBoardDatas) GetAttributeIntelligence() float32 {
	if m != nil {
		return m.AttributeIntelligence
	}
	return 0
}

func (m *UnitBoardDatas) GetAttack() int32 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *UnitBoardDatas) GetAttackSpeed() float32 {
	if m != nil {
		return m.AttackSpeed
	}
	return 0
}

func (m *UnitBoardDatas) GetAttackRange() float32 {
	if m != nil {
		return m.AttackRange
	}
	return 0
}

func (m *UnitBoardDatas) GetMoveSpeed() float32 {
	if m != nil {
		return m.MoveSpeed
	}
	return 0
}

func (m *UnitBoardDatas) GetMagicScale() float32 {
	if m != nil {
		return m.MagicScale
	}
	return 0
}

func (m *UnitBoardDatas) GetMPRegain() float32 {
	if m != nil {
		return m.MPRegain
	}
	return 0
}

func (m *UnitBoardDatas) GetPhysicalAmaor() float32 {
	if m != nil {
		return m.PhysicalAmaor
	}
	return 0
}

func (m *UnitBoardDatas) GetPhysicalResist() float32 {
	if m != nil {
		return m.PhysicalResist
	}
	return 0
}

func (m *UnitBoardDatas) GetMagicAmaor() float32 {
	if m != nil {
		return m.MagicAmaor
	}
	return 0
}

func (m *UnitBoardDatas) GetStatusAmaor() float32 {
	if m != nil {
		return m.StatusAmaor
	}
	return 0
}

func (m *UnitBoardDatas) GetDodge() float32 {
	if m != nil {
		return m.Dodge
	}
	return 0
}

func (m *UnitBoardDatas) GetHPRegain() float32 {
	if m != nil {
		return m.HPRegain
	}
	return 0
}

func (m *UnitBoardDatas) GetAttributePrimary() int32 {
	if m != nil {
		return m.AttributePrimary
	}
	return 0
}

func (m *UnitBoardDatas) GetDropItems() string {
	if m != nil {
		return m.DropItems
	}
	return ""
}

func (m *UnitBoardDatas) GetRemainExperience() int32 {
	if m != nil {
		return m.RemainExperience
	}
	return 0
}

func (m *UnitBoardDatas) GetEquips() []*UnitEquip {
	if m != nil {
		return m.Equips
	}
	return nil
}

// 获取单位面板详细信息
type CS_GetUnitInfo struct {
	UnitID               int32    `protobuf:"varint,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_GetUnitInfo) Reset()         { *m = CS_GetUnitInfo{} }
func (m *CS_GetUnitInfo) String() string { return proto.CompactTextString(m) }
func (*CS_GetUnitInfo) ProtoMessage()    {}
func (*CS_GetUnitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{8}
}
func (m *CS_GetUnitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_GetUnitInfo.Unmarshal(m, b)
}
func (m *CS_GetUnitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_GetUnitInfo.Marshal(b, m, deterministic)
}
func (dst *CS_GetUnitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_GetUnitInfo.Merge(dst, src)
}
func (m *CS_GetUnitInfo) XXX_Size() int {
	return xxx_messageInfo_CS_GetUnitInfo.Size(m)
}
func (m *CS_GetUnitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_GetUnitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CS_GetUnitInfo proto.InternalMessageInfo

func (m *CS_GetUnitInfo) GetUnitID() int32 {
	if m != nil {
		return m.UnitID
	}
	return 0
}

// 获取自己背包详细信息
type CS_GetBagInfo struct {
	UnitID               int32    `protobuf:"varint,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_GetBagInfo) Reset()         { *m = CS_GetBagInfo{} }
func (m *CS_GetBagInfo) String() string { return proto.CompactTextString(m) }
func (*CS_GetBagInfo) ProtoMessage()    {}
func (*CS_GetBagInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{9}
}
func (m *CS_GetBagInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_GetBagInfo.Unmarshal(m, b)
}
func (m *CS_GetBagInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_GetBagInfo.Marshal(b, m, deterministic)
}
func (dst *CS_GetBagInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_GetBagInfo.Merge(dst, src)
}
func (m *CS_GetBagInfo) XXX_Size() int {
	return xxx_messageInfo_CS_GetBagInfo.Size(m)
}
func (m *CS_GetBagInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_GetBagInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CS_GetBagInfo proto.InternalMessageInfo

func (m *CS_GetBagInfo) GetUnitID() int32 {
	if m != nil {
		return m.UnitID
	}
	return 0
}

// 交换道具位置 背包位置
type CS_ChangeItemPos struct {
	SrcPos               int32    `protobuf:"varint,1,opt,name=SrcPos,proto3" json:"SrcPos,omitempty"`
	DestPos              int32    `protobuf:"varint,2,opt,name=DestPos,proto3" json:"DestPos,omitempty"`
	SrcType              int32    `protobuf:"varint,3,opt,name=SrcType,proto3" json:"SrcType,omitempty"`
	DestType             int32    `protobuf:"varint,4,opt,name=DestType,proto3" json:"DestType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_ChangeItemPos) Reset()         { *m = CS_ChangeItemPos{} }
func (m *CS_ChangeItemPos) String() string { return proto.CompactTextString(m) }
func (*CS_ChangeItemPos) ProtoMessage()    {}
func (*CS_ChangeItemPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{10}
}
func (m *CS_ChangeItemPos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_ChangeItemPos.Unmarshal(m, b)
}
func (m *CS_ChangeItemPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_ChangeItemPos.Marshal(b, m, deterministic)
}
func (dst *CS_ChangeItemPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_ChangeItemPos.Merge(dst, src)
}
func (m *CS_ChangeItemPos) XXX_Size() int {
	return xxx_messageInfo_CS_ChangeItemPos.Size(m)
}
func (m *CS_ChangeItemPos) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_ChangeItemPos.DiscardUnknown(m)
}

var xxx_messageInfo_CS_ChangeItemPos proto.InternalMessageInfo

func (m *CS_ChangeItemPos) GetSrcPos() int32 {
	if m != nil {
		return m.SrcPos
	}
	return 0
}

func (m *CS_ChangeItemPos) GetDestPos() int32 {
	if m != nil {
		return m.DestPos
	}
	return 0
}

func (m *CS_ChangeItemPos) GetSrcType() int32 {
	if m != nil {
		return m.SrcType
	}
	return 0
}

func (m *CS_ChangeItemPos) GetDestType() int32 {
	if m != nil {
		return m.DestType
	}
	return 0
}

type SC_UnitInfo struct {
	UnitData             *UnitBoardDatas `protobuf:"bytes,1,opt,name=UnitData,proto3" json:"UnitData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SC_UnitInfo) Reset()         { *m = SC_UnitInfo{} }
func (m *SC_UnitInfo) String() string { return proto.CompactTextString(m) }
func (*SC_UnitInfo) ProtoMessage()    {}
func (*SC_UnitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{11}
}
func (m *SC_UnitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_UnitInfo.Unmarshal(m, b)
}
func (m *SC_UnitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_UnitInfo.Marshal(b, m, deterministic)
}
func (dst *SC_UnitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_UnitInfo.Merge(dst, src)
}
func (m *SC_UnitInfo) XXX_Size() int {
	return xxx_messageInfo_SC_UnitInfo.Size(m)
}
func (m *SC_UnitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_UnitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SC_UnitInfo proto.InternalMessageInfo

func (m *SC_UnitInfo) GetUnitData() *UnitBoardDatas {
	if m != nil {
		return m.UnitData
	}
	return nil
}

type SC_BagInfo struct {
	Equips               []*UnitEquip `protobuf:"bytes,1,rep,name=Equips,proto3" json:"Equips,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SC_BagInfo) Reset()         { *m = SC_BagInfo{} }
func (m *SC_BagInfo) String() string { return proto.CompactTextString(m) }
func (*SC_BagInfo) ProtoMessage()    {}
func (*SC_BagInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{12}
}
func (m *SC_BagInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_BagInfo.Unmarshal(m, b)
}
func (m *SC_BagInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_BagInfo.Marshal(b, m, deterministic)
}
func (dst *SC_BagInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_BagInfo.Merge(dst, src)
}
func (m *SC_BagInfo) XXX_Size() int {
	return xxx_messageInfo_SC_BagInfo.Size(m)
}
func (m *SC_BagInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_BagInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SC_BagInfo proto.InternalMessageInfo

func (m *SC_BagInfo) GetEquips() []*UnitEquip {
	if m != nil {
		return m.Equips
	}
	return nil
}

// 玩家升级技能
type CS_PlayerUpgradeSkill struct {
	TypeID               int32    `protobuf:"varint,1,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_PlayerUpgradeSkill) Reset()         { *m = CS_PlayerUpgradeSkill{} }
func (m *CS_PlayerUpgradeSkill) String() string { return proto.CompactTextString(m) }
func (*CS_PlayerUpgradeSkill) ProtoMessage()    {}
func (*CS_PlayerUpgradeSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{13}
}
func (m *CS_PlayerUpgradeSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_PlayerUpgradeSkill.Unmarshal(m, b)
}
func (m *CS_PlayerUpgradeSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_PlayerUpgradeSkill.Marshal(b, m, deterministic)
}
func (dst *CS_PlayerUpgradeSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_PlayerUpgradeSkill.Merge(dst, src)
}
func (m *CS_PlayerUpgradeSkill) XXX_Size() int {
	return xxx_messageInfo_CS_PlayerUpgradeSkill.Size(m)
}
func (m *CS_PlayerUpgradeSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_PlayerUpgradeSkill.DiscardUnknown(m)
}

var xxx_messageInfo_CS_PlayerUpgradeSkill proto.InternalMessageInfo

func (m *CS_PlayerUpgradeSkill) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

// 玩家移动操作
type CS_PlayerMove struct {
	IDs                  []int32  `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=Y,proto3" json:"Y,omitempty"`
	IsStart              bool     `protobuf:"varint,4,opt,name=IsStart,proto3" json:"IsStart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_PlayerMove) Reset()         { *m = CS_PlayerMove{} }
func (m *CS_PlayerMove) String() string { return proto.CompactTextString(m) }
func (*CS_PlayerMove) ProtoMessage()    {}
func (*CS_PlayerMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{14}
}
func (m *CS_PlayerMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_PlayerMove.Unmarshal(m, b)
}
func (m *CS_PlayerMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_PlayerMove.Marshal(b, m, deterministic)
}
func (dst *CS_PlayerMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_PlayerMove.Merge(dst, src)
}
func (m *CS_PlayerMove) XXX_Size() int {
	return xxx_messageInfo_CS_PlayerMove.Size(m)
}
func (m *CS_PlayerMove) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_PlayerMove.DiscardUnknown(m)
}

var xxx_messageInfo_CS_PlayerMove proto.InternalMessageInfo

func (m *CS_PlayerMove) GetIDs() []int32 {
	if m != nil {
		return m.IDs
	}
	return nil
}

func (m *CS_PlayerMove) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CS_PlayerMove) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CS_PlayerMove) GetIsStart() bool {
	if m != nil {
		return m.IsStart
	}
	return false
}

// 玩家攻击操作
type CS_PlayerAttack struct {
	IDs                  []int32  `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	TargetUnitID         int32    `protobuf:"varint,2,opt,name=TargetUnitID,proto3" json:"TargetUnitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_PlayerAttack) Reset()         { *m = CS_PlayerAttack{} }
func (m *CS_PlayerAttack) String() string { return proto.CompactTextString(m) }
func (*CS_PlayerAttack) ProtoMessage()    {}
func (*CS_PlayerAttack) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{15}
}
func (m *CS_PlayerAttack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_PlayerAttack.Unmarshal(m, b)
}
func (m *CS_PlayerAttack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_PlayerAttack.Marshal(b, m, deterministic)
}
func (dst *CS_PlayerAttack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_PlayerAttack.Merge(dst, src)
}
func (m *CS_PlayerAttack) XXX_Size() int {
	return xxx_messageInfo_CS_PlayerAttack.Size(m)
}
func (m *CS_PlayerAttack) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_PlayerAttack.DiscardUnknown(m)
}

var xxx_messageInfo_CS_PlayerAttack proto.InternalMessageInfo

func (m *CS_PlayerAttack) GetIDs() []int32 {
	if m != nil {
		return m.IDs
	}
	return nil
}

func (m *CS_PlayerAttack) GetTargetUnitID() int32 {
	if m != nil {
		return m.TargetUnitID
	}
	return 0
}

// 玩家技能操作(包括道具)
type CS_PlayerSkill struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SkillID              int32    `protobuf:"varint,2,opt,name=SkillID,proto3" json:"SkillID,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	TargetUnitID         int32    `protobuf:"varint,5,opt,name=TargetUnitID,proto3" json:"TargetUnitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_PlayerSkill) Reset()         { *m = CS_PlayerSkill{} }
func (m *CS_PlayerSkill) String() string { return proto.CompactTextString(m) }
func (*CS_PlayerSkill) ProtoMessage()    {}
func (*CS_PlayerSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{16}
}
func (m *CS_PlayerSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_PlayerSkill.Unmarshal(m, b)
}
func (m *CS_PlayerSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_PlayerSkill.Marshal(b, m, deterministic)
}
func (dst *CS_PlayerSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_PlayerSkill.Merge(dst, src)
}
func (m *CS_PlayerSkill) XXX_Size() int {
	return xxx_messageInfo_CS_PlayerSkill.Size(m)
}
func (m *CS_PlayerSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_PlayerSkill.DiscardUnknown(m)
}

var xxx_messageInfo_CS_PlayerSkill proto.InternalMessageInfo

func (m *CS_PlayerSkill) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CS_PlayerSkill) GetSkillID() int32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

func (m *CS_PlayerSkill) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CS_PlayerSkill) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CS_PlayerSkill) GetTargetUnitID() int32 {
	if m != nil {
		return m.TargetUnitID
	}
	return 0
}

// 玩家切换攻击模式
type CS_ChangeAttackMode struct {
	AttackMode           int32    `protobuf:"varint,1,opt,name=AttackMode,proto3" json:"AttackMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_ChangeAttackMode) Reset()         { *m = CS_ChangeAttackMode{} }
func (m *CS_ChangeAttackMode) String() string { return proto.CompactTextString(m) }
func (*CS_ChangeAttackMode) ProtoMessage()    {}
func (*CS_ChangeAttackMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{17}
}
func (m *CS_ChangeAttackMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_ChangeAttackMode.Unmarshal(m, b)
}
func (m *CS_ChangeAttackMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_ChangeAttackMode.Marshal(b, m, deterministic)
}
func (dst *CS_ChangeAttackMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_ChangeAttackMode.Merge(dst, src)
}
func (m *CS_ChangeAttackMode) XXX_Size() int {
	return xxx_messageInfo_CS_ChangeAttackMode.Size(m)
}
func (m *CS_ChangeAttackMode) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_ChangeAttackMode.DiscardUnknown(m)
}

var xxx_messageInfo_CS_ChangeAttackMode proto.InternalMessageInfo

func (m *CS_ChangeAttackMode) GetAttackMode() int32 {
	if m != nil {
		return m.AttackMode
	}
	return 0
}

// 组队操作
type CS_OrganizeTeam struct {
	Player1              int32    `protobuf:"varint,1,opt,name=Player1,proto3" json:"Player1,omitempty"`
	Player2              int32    `protobuf:"varint,2,opt,name=Player2,proto3" json:"Player2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_OrganizeTeam) Reset()         { *m = CS_OrganizeTeam{} }
func (m *CS_OrganizeTeam) String() string { return proto.CompactTextString(m) }
func (*CS_OrganizeTeam) ProtoMessage()    {}
func (*CS_OrganizeTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{18}
}
func (m *CS_OrganizeTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_OrganizeTeam.Unmarshal(m, b)
}
func (m *CS_OrganizeTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_OrganizeTeam.Marshal(b, m, deterministic)
}
func (dst *CS_OrganizeTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_OrganizeTeam.Merge(dst, src)
}
func (m *CS_OrganizeTeam) XXX_Size() int {
	return xxx_messageInfo_CS_OrganizeTeam.Size(m)
}
func (m *CS_OrganizeTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_OrganizeTeam.DiscardUnknown(m)
}

var xxx_messageInfo_CS_OrganizeTeam proto.InternalMessageInfo

func (m *CS_OrganizeTeam) GetPlayer1() int32 {
	if m != nil {
		return m.Player1
	}
	return 0
}

func (m *CS_OrganizeTeam) GetPlayer2() int32 {
	if m != nil {
		return m.Player2
	}
	return 0
}

// 组队请求
type SC_RequestTeam struct {
	SrcPlayerUID         int32    `protobuf:"varint,1,opt,name=SrcPlayerUID,proto3" json:"SrcPlayerUID,omitempty"`
	SrcName              string   `protobuf:"bytes,2,opt,name=SrcName,proto3" json:"SrcName,omitempty"`
	SrcUnitTypeID        int32    `protobuf:"varint,3,opt,name=SrcUnitTypeID,proto3" json:"SrcUnitTypeID,omitempty"`
	SrcLevel             int32    `protobuf:"varint,4,opt,name=SrcLevel,proto3" json:"SrcLevel,omitempty"`
	RequestType          int32    `protobuf:"varint,5,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_RequestTeam) Reset()         { *m = SC_RequestTeam{} }
func (m *SC_RequestTeam) String() string { return proto.CompactTextString(m) }
func (*SC_RequestTeam) ProtoMessage()    {}
func (*SC_RequestTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{19}
}
func (m *SC_RequestTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_RequestTeam.Unmarshal(m, b)
}
func (m *SC_RequestTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_RequestTeam.Marshal(b, m, deterministic)
}
func (dst *SC_RequestTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_RequestTeam.Merge(dst, src)
}
func (m *SC_RequestTeam) XXX_Size() int {
	return xxx_messageInfo_SC_RequestTeam.Size(m)
}
func (m *SC_RequestTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_RequestTeam.DiscardUnknown(m)
}

var xxx_messageInfo_SC_RequestTeam proto.InternalMessageInfo

func (m *SC_RequestTeam) GetSrcPlayerUID() int32 {
	if m != nil {
		return m.SrcPlayerUID
	}
	return 0
}

func (m *SC_RequestTeam) GetSrcName() string {
	if m != nil {
		return m.SrcName
	}
	return ""
}

func (m *SC_RequestTeam) GetSrcUnitTypeID() int32 {
	if m != nil {
		return m.SrcUnitTypeID
	}
	return 0
}

func (m *SC_RequestTeam) GetSrcLevel() int32 {
	if m != nil {
		return m.SrcLevel
	}
	return 0
}

func (m *SC_RequestTeam) GetRequestType() int32 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

// 回复组队请求
type CS_ResponseOrgTeam struct {
	SrcPlayerUID         int32    `protobuf:"varint,1,opt,name=SrcPlayerUID,proto3" json:"SrcPlayerUID,omitempty"`
	IsAgree              int32    `protobuf:"varint,2,opt,name=IsAgree,proto3" json:"IsAgree,omitempty"`
	RequestType          int32    `protobuf:"varint,3,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_ResponseOrgTeam) Reset()         { *m = CS_ResponseOrgTeam{} }
func (m *CS_ResponseOrgTeam) String() string { return proto.CompactTextString(m) }
func (*CS_ResponseOrgTeam) ProtoMessage()    {}
func (*CS_ResponseOrgTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{20}
}
func (m *CS_ResponseOrgTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_ResponseOrgTeam.Unmarshal(m, b)
}
func (m *CS_ResponseOrgTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_ResponseOrgTeam.Marshal(b, m, deterministic)
}
func (dst *CS_ResponseOrgTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_ResponseOrgTeam.Merge(dst, src)
}
func (m *CS_ResponseOrgTeam) XXX_Size() int {
	return xxx_messageInfo_CS_ResponseOrgTeam.Size(m)
}
func (m *CS_ResponseOrgTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_ResponseOrgTeam.DiscardUnknown(m)
}

var xxx_messageInfo_CS_ResponseOrgTeam proto.InternalMessageInfo

func (m *CS_ResponseOrgTeam) GetSrcPlayerUID() int32 {
	if m != nil {
		return m.SrcPlayerUID
	}
	return 0
}

func (m *CS_ResponseOrgTeam) GetIsAgree() int32 {
	if m != nil {
		return m.IsAgree
	}
	return 0
}

func (m *CS_ResponseOrgTeam) GetRequestType() int32 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

// 技能数据
type SkillDatas struct {
	TypeID                int32    `protobuf:"varint,1,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	Level                 int32    `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	RemainCDTime          float32  `protobuf:"fixed32,3,opt,name=RemainCDTime,proto3" json:"RemainCDTime,omitempty"`
	CanUpgrade            int32    `protobuf:"varint,4,opt,name=CanUpgrade,proto3" json:"CanUpgrade,omitempty"`
	Index                 int32    `protobuf:"varint,5,opt,name=Index,proto3" json:"Index,omitempty"`
	CastType              int32    `protobuf:"varint,6,opt,name=CastType,proto3" json:"CastType,omitempty"`
	CastTargetType        int32    `protobuf:"varint,7,opt,name=CastTargetType,proto3" json:"CastTargetType,omitempty"`
	UnitTargetTeam        int32    `protobuf:"varint,8,opt,name=UnitTargetTeam,proto3" json:"UnitTargetTeam,omitempty"`
	UnitTargetCamp        int32    `protobuf:"varint,9,opt,name=UnitTargetCamp,proto3" json:"UnitTargetCamp,omitempty"`
	NoCareMagicImmune     int32    `protobuf:"varint,10,opt,name=NoCareMagicImmune,proto3" json:"NoCareMagicImmune,omitempty"`
	CastRange             float32  `protobuf:"fixed32,11,opt,name=CastRange,proto3" json:"CastRange,omitempty"`
	Cooldown              float32  `protobuf:"fixed32,12,opt,name=Cooldown,proto3" json:"Cooldown,omitempty"`
	HurtRange             float32  `protobuf:"fixed32,13,opt,name=HurtRange,proto3" json:"HurtRange,omitempty"`
	ManaCost              int32    `protobuf:"varint,14,opt,name=ManaCost,proto3" json:"ManaCost,omitempty"`
	AttackAutoActive      int32    `protobuf:"varint,15,opt,name=AttackAutoActive,proto3" json:"AttackAutoActive,omitempty"`
	Visible               int32    `protobuf:"varint,16,opt,name=Visible,proto3" json:"Visible,omitempty"`
	RemainSkillCount      int32    `protobuf:"varint,17,opt,name=RemainSkillCount,proto3" json:"RemainSkillCount,omitempty"`
	MaxLevel              int32    `protobuf:"varint,18,opt,name=MaxLevel,proto3" json:"MaxLevel,omitempty"`
	RequiredLevel         int32    `protobuf:"varint,19,opt,name=RequiredLevel,proto3" json:"RequiredLevel,omitempty"`
	LevelsBetweenUpgrades int32    `protobuf:"varint,20,opt,name=LevelsBetweenUpgrades,proto3" json:"LevelsBetweenUpgrades,omitempty"`
	InitLevel             int32    `protobuf:"varint,21,opt,name=InitLevel,proto3" json:"InitLevel,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SkillDatas) Reset()         { *m = SkillDatas{} }
func (m *SkillDatas) String() string { return proto.CompactTextString(m) }
func (*SkillDatas) ProtoMessage()    {}
func (*SkillDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{21}
}
func (m *SkillDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillDatas.Unmarshal(m, b)
}
func (m *SkillDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillDatas.Marshal(b, m, deterministic)
}
func (dst *SkillDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillDatas.Merge(dst, src)
}
func (m *SkillDatas) XXX_Size() int {
	return xxx_messageInfo_SkillDatas.Size(m)
}
func (m *SkillDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillDatas.DiscardUnknown(m)
}

var xxx_messageInfo_SkillDatas proto.InternalMessageInfo

func (m *SkillDatas) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *SkillDatas) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *SkillDatas) GetRemainCDTime() float32 {
	if m != nil {
		return m.RemainCDTime
	}
	return 0
}

func (m *SkillDatas) GetCanUpgrade() int32 {
	if m != nil {
		return m.CanUpgrade
	}
	return 0
}

func (m *SkillDatas) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SkillDatas) GetCastType() int32 {
	if m != nil {
		return m.CastType
	}
	return 0
}

func (m *SkillDatas) GetCastTargetType() int32 {
	if m != nil {
		return m.CastTargetType
	}
	return 0
}

func (m *SkillDatas) GetUnitTargetTeam() int32 {
	if m != nil {
		return m.UnitTargetTeam
	}
	return 0
}

func (m *SkillDatas) GetUnitTargetCamp() int32 {
	if m != nil {
		return m.UnitTargetCamp
	}
	return 0
}

func (m *SkillDatas) GetNoCareMagicImmune() int32 {
	if m != nil {
		return m.NoCareMagicImmune
	}
	return 0
}

func (m *SkillDatas) GetCastRange() float32 {
	if m != nil {
		return m.CastRange
	}
	return 0
}

func (m *SkillDatas) GetCooldown() float32 {
	if m != nil {
		return m.Cooldown
	}
	return 0
}

func (m *SkillDatas) GetHurtRange() float32 {
	if m != nil {
		return m.HurtRange
	}
	return 0
}

func (m *SkillDatas) GetManaCost() int32 {
	if m != nil {
		return m.ManaCost
	}
	return 0
}

func (m *SkillDatas) GetAttackAutoActive() int32 {
	if m != nil {
		return m.AttackAutoActive
	}
	return 0
}

func (m *SkillDatas) GetVisible() int32 {
	if m != nil {
		return m.Visible
	}
	return 0
}

func (m *SkillDatas) GetRemainSkillCount() int32 {
	if m != nil {
		return m.RemainSkillCount
	}
	return 0
}

func (m *SkillDatas) GetMaxLevel() int32 {
	if m != nil {
		return m.MaxLevel
	}
	return 0
}

func (m *SkillDatas) GetRequiredLevel() int32 {
	if m != nil {
		return m.RequiredLevel
	}
	return 0
}

func (m *SkillDatas) GetLevelsBetweenUpgrades() int32 {
	if m != nil {
		return m.LevelsBetweenUpgrades
	}
	return 0
}

func (m *SkillDatas) GetInitLevel() int32 {
	if m != nil {
		return m.InitLevel
	}
	return 0
}

// buff数据
type BuffDatas struct {
	TypeID               int32    `protobuf:"varint,1,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	RemainTime           float32  `protobuf:"fixed32,2,opt,name=RemainTime,proto3" json:"RemainTime,omitempty"`
	Time                 float32  `protobuf:"fixed32,3,opt,name=Time,proto3" json:"Time,omitempty"`
	TagNum               int32    `protobuf:"varint,4,opt,name=TagNum,proto3" json:"TagNum,omitempty"`
	ConnectionType       int32    `protobuf:"varint,5,opt,name=ConnectionType,proto3" json:"ConnectionType,omitempty"`
	ConnectionX          float32  `protobuf:"fixed32,6,opt,name=ConnectionX,proto3" json:"ConnectionX,omitempty"`
	ConnectionY          float32  `protobuf:"fixed32,7,opt,name=ConnectionY,proto3" json:"ConnectionY,omitempty"`
	ConnectionZ          float32  `protobuf:"fixed32,8,opt,name=ConnectionZ,proto3" json:"ConnectionZ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuffDatas) Reset()         { *m = BuffDatas{} }
func (m *BuffDatas) String() string { return proto.CompactTextString(m) }
func (*BuffDatas) ProtoMessage()    {}
func (*BuffDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{22}
}
func (m *BuffDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuffDatas.Unmarshal(m, b)
}
func (m *BuffDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuffDatas.Marshal(b, m, deterministic)
}
func (dst *BuffDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuffDatas.Merge(dst, src)
}
func (m *BuffDatas) XXX_Size() int {
	return xxx_messageInfo_BuffDatas.Size(m)
}
func (m *BuffDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_BuffDatas.DiscardUnknown(m)
}

var xxx_messageInfo_BuffDatas proto.InternalMessageInfo

func (m *BuffDatas) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *BuffDatas) GetRemainTime() float32 {
	if m != nil {
		return m.RemainTime
	}
	return 0
}

func (m *BuffDatas) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BuffDatas) GetTagNum() int32 {
	if m != nil {
		return m.TagNum
	}
	return 0
}

func (m *BuffDatas) GetConnectionType() int32 {
	if m != nil {
		return m.ConnectionType
	}
	return 0
}

func (m *BuffDatas) GetConnectionX() float32 {
	if m != nil {
		return m.ConnectionX
	}
	return 0
}

func (m *BuffDatas) GetConnectionY() float32 {
	if m != nil {
		return m.ConnectionY
	}
	return 0
}

func (m *BuffDatas) GetConnectionZ() float32 {
	if m != nil {
		return m.ConnectionZ
	}
	return 0
}

// 单位数据
type UnitDatas struct {
	Name                 string        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32         `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	HP                   int32         `protobuf:"varint,3,opt,name=HP,proto3" json:"HP,omitempty"`
	MP                   int32         `protobuf:"varint,4,opt,name=MP,proto3" json:"MP,omitempty"`
	X                    float32       `protobuf:"fixed32,5,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32       `protobuf:"fixed32,6,opt,name=Y,proto3" json:"Y,omitempty"`
	ID                   int32         `protobuf:"varint,7,opt,name=ID,proto3" json:"ID,omitempty"`
	ModeType             string        `protobuf:"bytes,8,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	MaxHP                int32         `protobuf:"varint,9,opt,name=MaxHP,proto3" json:"MaxHP,omitempty"`
	MaxMP                int32         `protobuf:"varint,10,opt,name=MaxMP,proto3" json:"MaxMP,omitempty"`
	Experience           int32         `protobuf:"varint,11,opt,name=Experience,proto3" json:"Experience,omitempty"`
	MaxExperience        int32         `protobuf:"varint,12,opt,name=MaxExperience,proto3" json:"MaxExperience,omitempty"`
	ControlID            int32         `protobuf:"varint,13,opt,name=ControlID,proto3" json:"ControlID,omitempty"`
	AnimotorState        int32         `protobuf:"varint,14,opt,name=AnimotorState,proto3" json:"AnimotorState,omitempty"`
	AttackTime           float32       `protobuf:"fixed32,15,opt,name=AttackTime,proto3" json:"AttackTime,omitempty"`
	DirectionX           float32       `protobuf:"fixed32,16,opt,name=DirectionX,proto3" json:"DirectionX,omitempty"`
	DirectionY           float32       `protobuf:"fixed32,17,opt,name=DirectionY,proto3" json:"DirectionY,omitempty"`
	UnitType             int32         `protobuf:"varint,18,opt,name=UnitType,proto3" json:"UnitType,omitempty"`
	AttackAcpabilities   int32         `protobuf:"varint,19,opt,name=AttackAcpabilities,proto3" json:"AttackAcpabilities,omitempty"`
	AttackMode           int32         `protobuf:"varint,20,opt,name=AttackMode,proto3" json:"AttackMode,omitempty"`
	IsMain               int32         `protobuf:"varint,21,opt,name=IsMain,proto3" json:"IsMain,omitempty"`
	IsDeath              int32         `protobuf:"varint,22,opt,name=IsDeath,proto3" json:"IsDeath,omitempty"`
	Invisible            int32         `protobuf:"varint,23,opt,name=Invisible,proto3" json:"Invisible,omitempty"`
	Camp                 int32         `protobuf:"varint,24,opt,name=Camp,proto3" json:"Camp,omitempty"`
	IsMiss               bool          `protobuf:"varint,25,opt,name=IsMiss,proto3" json:"IsMiss,omitempty"`
	AnimotorPause        int32         `protobuf:"varint,26,opt,name=AnimotorPause,proto3" json:"AnimotorPause,omitempty"`
	SkillEnable          int32         `protobuf:"varint,27,opt,name=SkillEnable,proto3" json:"SkillEnable,omitempty"`
	ItemEnable           int32         `protobuf:"varint,28,opt,name=ItemEnable,proto3" json:"ItemEnable,omitempty"`
	Z                    float32       `protobuf:"fixed32,29,opt,name=Z,proto3" json:"Z,omitempty"`
	IsMirrorImage        int32         `protobuf:"varint,30,opt,name=IsMirrorImage,proto3" json:"IsMirrorImage,omitempty"`
	AttackRange          float32       `protobuf:"fixed32,31,opt,name=AttackRange,proto3" json:"AttackRange,omitempty"`
	AttackAnim           int32         `protobuf:"varint,32,opt,name=AttackAnim,proto3" json:"AttackAnim,omitempty"`
	TypeID               int32         `protobuf:"varint,33,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	RemainReviveTime     float32       `protobuf:"fixed32,34,opt,name=RemainReviveTime,proto3" json:"RemainReviveTime,omitempty"`
	SD                   []*SkillDatas `protobuf:"bytes,35,rep,name=SD,proto3" json:"SD,omitempty"`
	BD                   []*BuffDatas  `protobuf:"bytes,36,rep,name=BD,proto3" json:"BD,omitempty"`
	ISD                  []*SkillDatas `protobuf:"bytes,37,rep,name=ISD,proto3" json:"ISD,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnitDatas) Reset()         { *m = UnitDatas{} }
func (m *UnitDatas) String() string { return proto.CompactTextString(m) }
func (*UnitDatas) ProtoMessage()    {}
func (*UnitDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{23}
}
func (m *UnitDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitDatas.Unmarshal(m, b)
}
func (m *UnitDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitDatas.Marshal(b, m, deterministic)
}
func (dst *UnitDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitDatas.Merge(dst, src)
}
func (m *UnitDatas) XXX_Size() int {
	return xxx_messageInfo_UnitDatas.Size(m)
}
func (m *UnitDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitDatas.DiscardUnknown(m)
}

var xxx_messageInfo_UnitDatas proto.InternalMessageInfo

func (m *UnitDatas) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitDatas) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UnitDatas) GetHP() int32 {
	if m != nil {
		return m.HP
	}
	return 0
}

func (m *UnitDatas) GetMP() int32 {
	if m != nil {
		return m.MP
	}
	return 0
}

func (m *UnitDatas) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *UnitDatas) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *UnitDatas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UnitDatas) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

func (m *UnitDatas) GetMaxHP() int32 {
	if m != nil {
		return m.MaxHP
	}
	return 0
}

func (m *UnitDatas) GetMaxMP() int32 {
	if m != nil {
		return m.MaxMP
	}
	return 0
}

func (m *UnitDatas) GetExperience() int32 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func (m *UnitDatas) GetMaxExperience() int32 {
	if m != nil {
		return m.MaxExperience
	}
	return 0
}

func (m *UnitDatas) GetControlID() int32 {
	if m != nil {
		return m.ControlID
	}
	return 0
}

func (m *UnitDatas) GetAnimotorState() int32 {
	if m != nil {
		return m.AnimotorState
	}
	return 0
}

func (m *UnitDatas) GetAttackTime() float32 {
	if m != nil {
		return m.AttackTime
	}
	return 0
}

func (m *UnitDatas) GetDirectionX() float32 {
	if m != nil {
		return m.DirectionX
	}
	return 0
}

func (m *UnitDatas) GetDirectionY() float32 {
	if m != nil {
		return m.DirectionY
	}
	return 0
}

func (m *UnitDatas) GetUnitType() int32 {
	if m != nil {
		return m.UnitType
	}
	return 0
}

func (m *UnitDatas) GetAttackAcpabilities() int32 {
	if m != nil {
		return m.AttackAcpabilities
	}
	return 0
}

func (m *UnitDatas) GetAttackMode() int32 {
	if m != nil {
		return m.AttackMode
	}
	return 0
}

func (m *UnitDatas) GetIsMain() int32 {
	if m != nil {
		return m.IsMain
	}
	return 0
}

func (m *UnitDatas) GetIsDeath() int32 {
	if m != nil {
		return m.IsDeath
	}
	return 0
}

func (m *UnitDatas) GetInvisible() int32 {
	if m != nil {
		return m.Invisible
	}
	return 0
}

func (m *UnitDatas) GetCamp() int32 {
	if m != nil {
		return m.Camp
	}
	return 0
}

func (m *UnitDatas) GetIsMiss() bool {
	if m != nil {
		return m.IsMiss
	}
	return false
}

func (m *UnitDatas) GetAnimotorPause() int32 {
	if m != nil {
		return m.AnimotorPause
	}
	return 0
}

func (m *UnitDatas) GetSkillEnable() int32 {
	if m != nil {
		return m.SkillEnable
	}
	return 0
}

func (m *UnitDatas) GetItemEnable() int32 {
	if m != nil {
		return m.ItemEnable
	}
	return 0
}

func (m *UnitDatas) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *UnitDatas) GetIsMirrorImage() int32 {
	if m != nil {
		return m.IsMirrorImage
	}
	return 0
}

func (m *UnitDatas) GetAttackRange() float32 {
	if m != nil {
		return m.AttackRange
	}
	return 0
}

func (m *UnitDatas) GetAttackAnim() int32 {
	if m != nil {
		return m.AttackAnim
	}
	return 0
}

func (m *UnitDatas) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *UnitDatas) GetRemainReviveTime() float32 {
	if m != nil {
		return m.RemainReviveTime
	}
	return 0
}

func (m *UnitDatas) GetSD() []*SkillDatas {
	if m != nil {
		return m.SD
	}
	return nil
}

func (m *UnitDatas) GetBD() []*BuffDatas {
	if m != nil {
		return m.BD
	}
	return nil
}

func (m *UnitDatas) GetISD() []*SkillDatas {
	if m != nil {
		return m.ISD
	}
	return nil
}

type BulletDatas struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ModeType             string   `protobuf:"bytes,2,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float32  `protobuf:"fixed32,5,opt,name=Z,proto3" json:"Z,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=State,proto3" json:"State,omitempty"`
	StartX               float32  `protobuf:"fixed32,7,opt,name=StartX,proto3" json:"StartX,omitempty"`
	StartY               float32  `protobuf:"fixed32,8,opt,name=StartY,proto3" json:"StartY,omitempty"`
	StartZ               float32  `protobuf:"fixed32,9,opt,name=StartZ,proto3" json:"StartZ,omitempty"`
	EndX                 float32  `protobuf:"fixed32,10,opt,name=EndX,proto3" json:"EndX,omitempty"`
	EndY                 float32  `protobuf:"fixed32,11,opt,name=EndY,proto3" json:"EndY,omitempty"`
	EndZ                 float32  `protobuf:"fixed32,12,opt,name=EndZ,proto3" json:"EndZ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulletDatas) Reset()         { *m = BulletDatas{} }
func (m *BulletDatas) String() string { return proto.CompactTextString(m) }
func (*BulletDatas) ProtoMessage()    {}
func (*BulletDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{24}
}
func (m *BulletDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulletDatas.Unmarshal(m, b)
}
func (m *BulletDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulletDatas.Marshal(b, m, deterministic)
}
func (dst *BulletDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulletDatas.Merge(dst, src)
}
func (m *BulletDatas) XXX_Size() int {
	return xxx_messageInfo_BulletDatas.Size(m)
}
func (m *BulletDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_BulletDatas.DiscardUnknown(m)
}

var xxx_messageInfo_BulletDatas proto.InternalMessageInfo

func (m *BulletDatas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BulletDatas) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

func (m *BulletDatas) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BulletDatas) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BulletDatas) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *BulletDatas) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *BulletDatas) GetStartX() float32 {
	if m != nil {
		return m.StartX
	}
	return 0
}

func (m *BulletDatas) GetStartY() float32 {
	if m != nil {
		return m.StartY
	}
	return 0
}

func (m *BulletDatas) GetStartZ() float32 {
	if m != nil {
		return m.StartZ
	}
	return 0
}

func (m *BulletDatas) GetEndX() float32 {
	if m != nil {
		return m.EndX
	}
	return 0
}

func (m *BulletDatas) GetEndY() float32 {
	if m != nil {
		return m.EndY
	}
	return 0
}

func (m *BulletDatas) GetEndZ() float32 {
	if m != nil {
		return m.EndZ
	}
	return 0
}

type SceneItemDatas struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TypeID               int32    `protobuf:"varint,2,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneItemDatas) Reset()         { *m = SceneItemDatas{} }
func (m *SceneItemDatas) String() string { return proto.CompactTextString(m) }
func (*SceneItemDatas) ProtoMessage()    {}
func (*SceneItemDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{25}
}
func (m *SceneItemDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneItemDatas.Unmarshal(m, b)
}
func (m *SceneItemDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneItemDatas.Marshal(b, m, deterministic)
}
func (dst *SceneItemDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneItemDatas.Merge(dst, src)
}
func (m *SceneItemDatas) XXX_Size() int {
	return xxx_messageInfo_SceneItemDatas.Size(m)
}
func (m *SceneItemDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneItemDatas.DiscardUnknown(m)
}

var xxx_messageInfo_SceneItemDatas proto.InternalMessageInfo

func (m *SceneItemDatas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SceneItemDatas) GetTypeID() int32 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *SceneItemDatas) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SceneItemDatas) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type HaloDatas struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ModeType             string   `protobuf:"bytes,2,opt,name=ModeType,proto3" json:"ModeType,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float32  `protobuf:"fixed32,5,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HaloDatas) Reset()         { *m = HaloDatas{} }
func (m *HaloDatas) String() string { return proto.CompactTextString(m) }
func (*HaloDatas) ProtoMessage()    {}
func (*HaloDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{26}
}
func (m *HaloDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HaloDatas.Unmarshal(m, b)
}
func (m *HaloDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HaloDatas.Marshal(b, m, deterministic)
}
func (dst *HaloDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HaloDatas.Merge(dst, src)
}
func (m *HaloDatas) XXX_Size() int {
	return xxx_messageInfo_HaloDatas.Size(m)
}
func (m *HaloDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_HaloDatas.DiscardUnknown(m)
}

var xxx_messageInfo_HaloDatas proto.InternalMessageInfo

func (m *HaloDatas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *HaloDatas) GetModeType() string {
	if m != nil {
		return m.ModeType
	}
	return ""
}

func (m *HaloDatas) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *HaloDatas) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *HaloDatas) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type MsgUserEnterScene struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ConnectId            int32    `protobuf:"varint,2,opt,name=ConnectId,proto3" json:"ConnectId,omitempty"`
	SrcServerName        string   `protobuf:"bytes,3,opt,name=SrcServerName,proto3" json:"SrcServerName,omitempty"`
	DestServerName       string   `protobuf:"bytes,4,opt,name=DestServerName,proto3" json:"DestServerName,omitempty"`
	SceneID              int32    `protobuf:"varint,5,opt,name=SceneID,proto3" json:"SceneID,omitempty"`
	Datas                []byte   `protobuf:"bytes,6,opt,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUserEnterScene) Reset()         { *m = MsgUserEnterScene{} }
func (m *MsgUserEnterScene) String() string { return proto.CompactTextString(m) }
func (*MsgUserEnterScene) ProtoMessage()    {}
func (*MsgUserEnterScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{27}
}
func (m *MsgUserEnterScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUserEnterScene.Unmarshal(m, b)
}
func (m *MsgUserEnterScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUserEnterScene.Marshal(b, m, deterministic)
}
func (dst *MsgUserEnterScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUserEnterScene.Merge(dst, src)
}
func (m *MsgUserEnterScene) XXX_Size() int {
	return xxx_messageInfo_MsgUserEnterScene.Size(m)
}
func (m *MsgUserEnterScene) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUserEnterScene.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUserEnterScene proto.InternalMessageInfo

func (m *MsgUserEnterScene) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgUserEnterScene) GetConnectId() int32 {
	if m != nil {
		return m.ConnectId
	}
	return 0
}

func (m *MsgUserEnterScene) GetSrcServerName() string {
	if m != nil {
		return m.SrcServerName
	}
	return ""
}

func (m *MsgUserEnterScene) GetDestServerName() string {
	if m != nil {
		return m.DestServerName
	}
	return ""
}

func (m *MsgUserEnterScene) GetSceneID() int32 {
	if m != nil {
		return m.SceneID
	}
	return 0
}

func (m *MsgUserEnterScene) GetDatas() []byte {
	if m != nil {
		return m.Datas
	}
	return nil
}

// 玩家自己造成的伤害数据
type MsgPlayerHurt struct {
	HurtUnitID           int32    `protobuf:"varint,1,opt,name=HurtUnitID,proto3" json:"HurtUnitID,omitempty"`
	HurtAllValue         int32    `protobuf:"varint,2,opt,name=HurtAllValue,proto3" json:"HurtAllValue,omitempty"`
	HurtMagicValue       int32    `protobuf:"varint,3,opt,name=HurtMagicValue,proto3" json:"HurtMagicValue,omitempty"`
	IsCrit               int32    `protobuf:"varint,4,opt,name=IsCrit,proto3" json:"IsCrit,omitempty"`
	GetGold              int32    `protobuf:"varint,5,opt,name=GetGold,proto3" json:"GetGold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPlayerHurt) Reset()         { *m = MsgPlayerHurt{} }
func (m *MsgPlayerHurt) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerHurt) ProtoMessage()    {}
func (*MsgPlayerHurt) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{28}
}
func (m *MsgPlayerHurt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerHurt.Unmarshal(m, b)
}
func (m *MsgPlayerHurt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerHurt.Marshal(b, m, deterministic)
}
func (dst *MsgPlayerHurt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerHurt.Merge(dst, src)
}
func (m *MsgPlayerHurt) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerHurt.Size(m)
}
func (m *MsgPlayerHurt) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerHurt.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerHurt proto.InternalMessageInfo

func (m *MsgPlayerHurt) GetHurtUnitID() int32 {
	if m != nil {
		return m.HurtUnitID
	}
	return 0
}

func (m *MsgPlayerHurt) GetHurtAllValue() int32 {
	if m != nil {
		return m.HurtAllValue
	}
	return 0
}

func (m *MsgPlayerHurt) GetHurtMagicValue() int32 {
	if m != nil {
		return m.HurtMagicValue
	}
	return 0
}

func (m *MsgPlayerHurt) GetIsCrit() int32 {
	if m != nil {
		return m.IsCrit
	}
	return 0
}

func (m *MsgPlayerHurt) GetGetGold() int32 {
	if m != nil {
		return m.GetGold
	}
	return 0
}

// 每帧更新单位数据
type SC_Update struct {
	CurFrame             int32             `protobuf:"varint,1,opt,name=CurFrame,proto3" json:"CurFrame,omitempty"`
	NewUnits             []*UnitDatas      `protobuf:"bytes,2,rep,name=NewUnits,proto3" json:"NewUnits,omitempty"`
	OldUnits             []*UnitDatas      `protobuf:"bytes,3,rep,name=OldUnits,proto3" json:"OldUnits,omitempty"`
	RemoveUnits          []int32           `protobuf:"varint,4,rep,packed,name=RemoveUnits,proto3" json:"RemoveUnits,omitempty"`
	NewBullets           []*BulletDatas    `protobuf:"bytes,5,rep,name=NewBullets,proto3" json:"NewBullets,omitempty"`
	OldBullets           []*BulletDatas    `protobuf:"bytes,6,rep,name=OldBullets,proto3" json:"OldBullets,omitempty"`
	RemoveBullets        []int32           `protobuf:"varint,7,rep,packed,name=RemoveBullets,proto3" json:"RemoveBullets,omitempty"`
	NewHalos             []*HaloDatas      `protobuf:"bytes,8,rep,name=NewHalos,proto3" json:"NewHalos,omitempty"`
	OldHalos             []*HaloDatas      `protobuf:"bytes,9,rep,name=OldHalos,proto3" json:"OldHalos,omitempty"`
	RemoveHalos          []int32           `protobuf:"varint,10,rep,packed,name=RemoveHalos,proto3" json:"RemoveHalos,omitempty"`
	NewSceneItems        []*SceneItemDatas `protobuf:"bytes,11,rep,name=NewSceneItems,proto3" json:"NewSceneItems,omitempty"`
	RemoveSceneItems     []int32           `protobuf:"varint,12,rep,packed,name=RemoveSceneItems,proto3" json:"RemoveSceneItems,omitempty"`
	PlayerHurt           []*MsgPlayerHurt  `protobuf:"bytes,13,rep,name=PlayerHurt,proto3" json:"PlayerHurt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SC_Update) Reset()         { *m = SC_Update{} }
func (m *SC_Update) String() string { return proto.CompactTextString(m) }
func (*SC_Update) ProtoMessage()    {}
func (*SC_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{29}
}
func (m *SC_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Update.Unmarshal(m, b)
}
func (m *SC_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Update.Marshal(b, m, deterministic)
}
func (dst *SC_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Update.Merge(dst, src)
}
func (m *SC_Update) XXX_Size() int {
	return xxx_messageInfo_SC_Update.Size(m)
}
func (m *SC_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Update.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Update proto.InternalMessageInfo

func (m *SC_Update) GetCurFrame() int32 {
	if m != nil {
		return m.CurFrame
	}
	return 0
}

func (m *SC_Update) GetNewUnits() []*UnitDatas {
	if m != nil {
		return m.NewUnits
	}
	return nil
}

func (m *SC_Update) GetOldUnits() []*UnitDatas {
	if m != nil {
		return m.OldUnits
	}
	return nil
}

func (m *SC_Update) GetRemoveUnits() []int32 {
	if m != nil {
		return m.RemoveUnits
	}
	return nil
}

func (m *SC_Update) GetNewBullets() []*BulletDatas {
	if m != nil {
		return m.NewBullets
	}
	return nil
}

func (m *SC_Update) GetOldBullets() []*BulletDatas {
	if m != nil {
		return m.OldBullets
	}
	return nil
}

func (m *SC_Update) GetRemoveBullets() []int32 {
	if m != nil {
		return m.RemoveBullets
	}
	return nil
}

func (m *SC_Update) GetNewHalos() []*HaloDatas {
	if m != nil {
		return m.NewHalos
	}
	return nil
}

func (m *SC_Update) GetOldHalos() []*HaloDatas {
	if m != nil {
		return m.OldHalos
	}
	return nil
}

func (m *SC_Update) GetRemoveHalos() []int32 {
	if m != nil {
		return m.RemoveHalos
	}
	return nil
}

func (m *SC_Update) GetNewSceneItems() []*SceneItemDatas {
	if m != nil {
		return m.NewSceneItems
	}
	return nil
}

func (m *SC_Update) GetRemoveSceneItems() []int32 {
	if m != nil {
		return m.RemoveSceneItems
	}
	return nil
}

func (m *SC_Update) GetPlayerHurt() []*MsgPlayerHurt {
	if m != nil {
		return m.PlayerHurt
	}
	return nil
}

// 玩家进入新场景时的场景信息
type SC_NewScene struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	LogicFps             int32    `protobuf:"varint,2,opt,name=LogicFps,proto3" json:"LogicFps,omitempty"`
	CurFrame             int32    `protobuf:"varint,3,opt,name=CurFrame,proto3" json:"CurFrame,omitempty"`
	ServerName           string   `protobuf:"bytes,4,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	SceneID              int32    `protobuf:"varint,5,opt,name=SceneID,proto3" json:"SceneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_NewScene) Reset()         { *m = SC_NewScene{} }
func (m *SC_NewScene) String() string { return proto.CompactTextString(m) }
func (*SC_NewScene) ProtoMessage()    {}
func (*SC_NewScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{30}
}
func (m *SC_NewScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_NewScene.Unmarshal(m, b)
}
func (m *SC_NewScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_NewScene.Marshal(b, m, deterministic)
}
func (dst *SC_NewScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_NewScene.Merge(dst, src)
}
func (m *SC_NewScene) XXX_Size() int {
	return xxx_messageInfo_SC_NewScene.Size(m)
}
func (m *SC_NewScene) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_NewScene.DiscardUnknown(m)
}

var xxx_messageInfo_SC_NewScene proto.InternalMessageInfo

func (m *SC_NewScene) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SC_NewScene) GetLogicFps() int32 {
	if m != nil {
		return m.LogicFps
	}
	return 0
}

func (m *SC_NewScene) GetCurFrame() int32 {
	if m != nil {
		return m.CurFrame
	}
	return 0
}

func (m *SC_NewScene) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SC_NewScene) GetSceneID() int32 {
	if m != nil {
		return m.SceneID
	}
	return 0
}

// 单位数据
type CharacterBaseDatas struct {
	Characterid          int32    `protobuf:"varint,1,opt,name=Characterid,proto3" json:"Characterid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Typeid               int32    `protobuf:"varint,3,opt,name=Typeid,proto3" json:"Typeid,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterBaseDatas) Reset()         { *m = CharacterBaseDatas{} }
func (m *CharacterBaseDatas) String() string { return proto.CompactTextString(m) }
func (*CharacterBaseDatas) ProtoMessage()    {}
func (*CharacterBaseDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{31}
}
func (m *CharacterBaseDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterBaseDatas.Unmarshal(m, b)
}
func (m *CharacterBaseDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterBaseDatas.Marshal(b, m, deterministic)
}
func (dst *CharacterBaseDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterBaseDatas.Merge(dst, src)
}
func (m *CharacterBaseDatas) XXX_Size() int {
	return xxx_messageInfo_CharacterBaseDatas.Size(m)
}
func (m *CharacterBaseDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterBaseDatas.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterBaseDatas proto.InternalMessageInfo

func (m *CharacterBaseDatas) GetCharacterid() int32 {
	if m != nil {
		return m.Characterid
	}
	return 0
}

func (m *CharacterBaseDatas) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CharacterBaseDatas) GetTypeid() int32 {
	if m != nil {
		return m.Typeid
	}
	return 0
}

func (m *CharacterBaseDatas) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type SC_Logined struct {
	Code                 int32                 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Uid                  int32                 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Error                string                `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Characters           []*CharacterBaseDatas `protobuf:"bytes,4,rep,name=Characters,proto3" json:"Characters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SC_Logined) Reset()         { *m = SC_Logined{} }
func (m *SC_Logined) String() string { return proto.CompactTextString(m) }
func (*SC_Logined) ProtoMessage()    {}
func (*SC_Logined) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{32}
}
func (m *SC_Logined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Logined.Unmarshal(m, b)
}
func (m *SC_Logined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Logined.Marshal(b, m, deterministic)
}
func (dst *SC_Logined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Logined.Merge(dst, src)
}
func (m *SC_Logined) XXX_Size() int {
	return xxx_messageInfo_SC_Logined.Size(m)
}
func (m *SC_Logined) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Logined.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Logined proto.InternalMessageInfo

func (m *SC_Logined) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SC_Logined) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SC_Logined) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SC_Logined) GetCharacters() []*CharacterBaseDatas {
	if m != nil {
		return m.Characters
	}
	return nil
}

// 选择角色结果()
type SC_SelectCharacterResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Characterid          int32    `protobuf:"varint,2,opt,name=Characterid,proto3" json:"Characterid,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_SelectCharacterResult) Reset()         { *m = SC_SelectCharacterResult{} }
func (m *SC_SelectCharacterResult) String() string { return proto.CompactTextString(m) }
func (*SC_SelectCharacterResult) ProtoMessage()    {}
func (*SC_SelectCharacterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_617aaba9bf0c07c7, []int{33}
}
func (m *SC_SelectCharacterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_SelectCharacterResult.Unmarshal(m, b)
}
func (m *SC_SelectCharacterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_SelectCharacterResult.Marshal(b, m, deterministic)
}
func (dst *SC_SelectCharacterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_SelectCharacterResult.Merge(dst, src)
}
func (m *SC_SelectCharacterResult) XXX_Size() int {
	return xxx_messageInfo_SC_SelectCharacterResult.Size(m)
}
func (m *SC_SelectCharacterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_SelectCharacterResult.DiscardUnknown(m)
}

var xxx_messageInfo_SC_SelectCharacterResult proto.InternalMessageInfo

func (m *SC_SelectCharacterResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SC_SelectCharacterResult) GetCharacterid() int32 {
	if m != nil {
		return m.Characterid
	}
	return 0
}

func (m *SC_SelectCharacterResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBase)(nil), "protomsg.MsgBase")
	proto.RegisterType((*MsgRegisterToGate)(nil), "protomsg.MsgRegisterToGate")
	proto.RegisterType((*CS_MsgQuickLogin)(nil), "protomsg.CS_MsgQuickLogin")
	proto.RegisterType((*CS_Login)(nil), "protomsg.CS_Login")
	proto.RegisterType((*CS_SelectCharacter)(nil), "protomsg.CS_SelectCharacter")
	proto.RegisterType((*CS_LodingScene)(nil), "protomsg.CS_LodingScene")
	proto.RegisterType((*UnitEquip)(nil), "protomsg.UnitEquip")
	proto.RegisterType((*UnitBoardDatas)(nil), "protomsg.UnitBoardDatas")
	proto.RegisterType((*CS_GetUnitInfo)(nil), "protomsg.CS_GetUnitInfo")
	proto.RegisterType((*CS_GetBagInfo)(nil), "protomsg.CS_GetBagInfo")
	proto.RegisterType((*CS_ChangeItemPos)(nil), "protomsg.CS_ChangeItemPos")
	proto.RegisterType((*SC_UnitInfo)(nil), "protomsg.SC_UnitInfo")
	proto.RegisterType((*SC_BagInfo)(nil), "protomsg.SC_BagInfo")
	proto.RegisterType((*CS_PlayerUpgradeSkill)(nil), "protomsg.CS_PlayerUpgradeSkill")
	proto.RegisterType((*CS_PlayerMove)(nil), "protomsg.CS_PlayerMove")
	proto.RegisterType((*CS_PlayerAttack)(nil), "protomsg.CS_PlayerAttack")
	proto.RegisterType((*CS_PlayerSkill)(nil), "protomsg.CS_PlayerSkill")
	proto.RegisterType((*CS_ChangeAttackMode)(nil), "protomsg.CS_ChangeAttackMode")
	proto.RegisterType((*CS_OrganizeTeam)(nil), "protomsg.CS_OrganizeTeam")
	proto.RegisterType((*SC_RequestTeam)(nil), "protomsg.SC_RequestTeam")
	proto.RegisterType((*CS_ResponseOrgTeam)(nil), "protomsg.CS_ResponseOrgTeam")
	proto.RegisterType((*SkillDatas)(nil), "protomsg.SkillDatas")
	proto.RegisterType((*BuffDatas)(nil), "protomsg.BuffDatas")
	proto.RegisterType((*UnitDatas)(nil), "protomsg.UnitDatas")
	proto.RegisterType((*BulletDatas)(nil), "protomsg.BulletDatas")
	proto.RegisterType((*SceneItemDatas)(nil), "protomsg.SceneItemDatas")
	proto.RegisterType((*HaloDatas)(nil), "protomsg.HaloDatas")
	proto.RegisterType((*MsgUserEnterScene)(nil), "protomsg.MsgUserEnterScene")
	proto.RegisterType((*MsgPlayerHurt)(nil), "protomsg.MsgPlayerHurt")
	proto.RegisterType((*SC_Update)(nil), "protomsg.SC_Update")
	proto.RegisterType((*SC_NewScene)(nil), "protomsg.SC_NewScene")
	proto.RegisterType((*CharacterBaseDatas)(nil), "protomsg.CharacterBaseDatas")
	proto.RegisterType((*SC_Logined)(nil), "protomsg.SC_Logined")
	proto.RegisterType((*SC_SelectCharacterResult)(nil), "protomsg.SC_SelectCharacterResult")
}

func init() { proto.RegisterFile("protobuf/msg.proto", fileDescriptor_617aaba9bf0c07c7) }

var fileDescriptor_617aaba9bf0c07c7 = []byte{
	// 2323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xef, 0x6e, 0xdb, 0xc8,
	0x11, 0x87, 0x68, 0xd3, 0x91, 0xd6, 0x7f, 0x92, 0x30, 0xce, 0x1d, 0x9b, 0x4b, 0x53, 0x97, 0x97,
	0x5e, 0x83, 0x6b, 0x91, 0xa0, 0xe9, 0x05, 0x45, 0x81, 0xa2, 0x80, 0x4d, 0x39, 0xb1, 0x80, 0xc8,
	0x51, 0x48, 0xe7, 0x2e, 0x0e, 0x0a, 0xb8, 0x6b, 0x69, 0x4d, 0x13, 0xa1, 0x48, 0xdd, 0x72, 0xe5,
	0xd8, 0xf9, 0xde, 0xbe, 0x40, 0xbf, 0xf4, 0x25, 0x0a, 0x14, 0x7d, 0x83, 0xbe, 0x42, 0x5f, 0xa0,
	0x5f, 0xfb, 0x12, 0x05, 0x8a, 0x99, 0xd9, 0x25, 0x97, 0x94, 0xea, 0x6b, 0x3f, 0xdc, 0x27, 0x71,
	0x7e, 0x3b, 0xbb, 0x3b, 0x33, 0x3b, 0xff, 0x76, 0xc5, 0xbc, 0x99, 0x2c, 0x54, 0x71, 0x3a, 0x3f,
	0x7b, 0x32, 0x2d, 0x93, 0xc7, 0x48, 0x78, 0x5d, 0xfc, 0x99, 0x96, 0x49, 0xf0, 0x87, 0x0e, 0xbb,
	0x31, 0x2c, 0x93, 0x3d, 0x5e, 0x0a, 0xef, 0x1e, 0xeb, 0x0e, 0x8b, 0x89, 0x38, 0xba, 0x9a, 0x09,
	0xbf, 0xb3, 0xd3, 0x79, 0xd4, 0x8b, 0x2a, 0xda, 0xbb, 0xc5, 0x56, 0xde, 0xa4, 0x13, 0xdf, 0xd9,
	0xe9, 0x3c, 0x72, 0x23, 0xf8, 0xf4, 0x7c, 0x9c, 0x88, 0xcc, 0x2b, 0xc8, 0x6c, 0x48, 0xef, 0x3e,
	0xeb, 0x85, 0x45, 0x9e, 0x8b, 0xb1, 0x1a, 0x4c, 0xfc, 0x55, 0x9c, 0x51, 0x03, 0xde, 0x36, 0x73,
	0xfb, 0x5c, 0xf1, 0xd2, 0x77, 0x77, 0x3a, 0x8f, 0x36, 0x22, 0x22, 0x82, 0x27, 0xec, 0xf6, 0xb0,
	0x4c, 0x22, 0x91, 0xa4, 0xa5, 0x12, 0xf2, 0xa8, 0x78, 0xc1, 0xd5, 0xb5, 0x02, 0x05, 0xbf, 0x67,
	0xb7, 0xc2, 0xf8, 0x64, 0x58, 0x26, 0xaf, 0xe7, 0xe9, 0xf8, 0xfd, 0xcb, 0x22, 0x49, 0x73, 0xe0,
	0x1f, 0x65, 0x5c, 0x9d, 0x15, 0x72, 0x6a, 0xf8, 0x0d, 0x0d, 0x42, 0x0d, 0xf9, 0xf8, 0x3c, 0xcd,
	0x85, 0x56, 0xa3, 0x17, 0xd5, 0x80, 0xe7, 0xb1, 0xd5, 0x43, 0x3e, 0x35, 0x9a, 0xe0, 0x77, 0xf0,
	0xe7, 0x0e, 0xeb, 0x86, 0xf1, 0x09, 0x2d, 0xbd, 0xc3, 0xd6, 0x47, 0xe7, 0x45, 0x2e, 0xf2, 0xf9,
	0xf4, 0x54, 0x48, 0xbd, 0xba, 0x0d, 0x35, 0x36, 0x77, 0xae, 0xdb, 0x7c, 0xa5, 0xbd, 0xf9, 0x67,
	0xac, 0xf7, 0x8d, 0x18, 0x9f, 0x73, 0x75, 0x92, 0x92, 0xbd, 0x7a, 0x51, 0x97, 0x80, 0xc1, 0xc4,
	0xbb, 0xc3, 0xdc, 0xd7, 0xaf, 0x61, 0xc0, 0x25, 0xd1, 0x5e, 0xbf, 0x1e, 0x4c, 0x82, 0xdf, 0x31,
	0x2f, 0x8c, 0x4f, 0x62, 0x91, 0x89, 0xb1, 0x0a, 0xcf, 0xb9, 0xe4, 0x63, 0x25, 0xa4, 0xf7, 0x9c,
	0xdd, 0x6c, 0x41, 0x28, 0xe7, 0xfa, 0xd3, 0xfb, 0x8f, 0xcd, 0x79, 0x3f, 0xae, 0x86, 0xe0, 0xc4,
	0xd1, 0xf4, 0x51, 0x7b, 0x52, 0xf0, 0x25, 0xdb, 0x42, 0xbd, 0x27, 0x69, 0x9e, 0xc4, 0x63, 0x91,
	0x0b, 0x38, 0x6b, 0xfc, 0x18, 0xf4, 0x71, 0x45, 0x37, 0x32, 0x64, 0xf0, 0x8c, 0xf5, 0xde, 0xe4,
	0xa9, 0xda, 0xff, 0x76, 0x9e, 0xce, 0xc0, 0x49, 0x46, 0x45, 0xa9, 0x59, 0xe0, 0xd3, 0xfb, 0x84,
	0xad, 0x1d, 0x5d, 0xcd, 0x26, 0x83, 0xbe, 0xf6, 0x1c, 0x4d, 0x05, 0xff, 0x74, 0xd9, 0x16, 0xcc,
	0xdb, 0x2b, 0xb8, 0x9c, 0xa0, 0x18, 0xde, 0x16, 0x73, 0xaa, 0xe5, 0x9d, 0x41, 0xbf, 0x3a, 0x12,
	0xa7, 0x3e, 0x12, 0xef, 0xe7, 0xec, 0xf6, 0xae, 0x52, 0x32, 0x3d, 0x9d, 0x2b, 0x11, 0x2b, 0x29,
	0xf2, 0x44, 0x9d, 0xa3, 0x3d, 0x9d, 0x68, 0x71, 0xc0, 0xfb, 0x92, 0xdd, 0xaa, 0xc0, 0xdd, 0x24,
	0xcd, 0x52, 0x75, 0x85, 0xe6, 0x75, 0xa2, 0x05, 0xdc, 0xfb, 0x8a, 0xdd, 0xad, 0xb0, 0x41, 0xae,
	0x44, 0x96, 0xa5, 0x89, 0xc8, 0xc7, 0x02, 0xcd, 0xee, 0x44, 0xcb, 0x07, 0x41, 0xbd, 0x5d, 0xa5,
	0xf8, 0xf8, 0xbd, 0xbf, 0x46, 0xea, 0x11, 0x05, 0xde, 0x42, 0x5f, 0xf1, 0x4c, 0x88, 0x89, 0x7f,
	0x03, 0xd7, 0xb0, 0xa1, 0x9a, 0x23, 0xe2, 0x79, 0x22, 0xfc, 0xae, 0xcd, 0x81, 0x10, 0xfa, 0x4c,
	0x71, 0x21, 0x68, 0x85, 0x1e, 0x8e, 0xd7, 0x80, 0xf7, 0x80, 0xb1, 0x21, 0x4f, 0xd2, 0x71, 0x3c,
	0xe6, 0x99, 0xf0, 0x19, 0x0e, 0x5b, 0x08, 0x86, 0xce, 0x28, 0x12, 0x09, 0x4f, 0x73, 0x7f, 0x1d,
	0x47, 0x2b, 0xda, 0x7b, 0xc8, 0x36, 0x47, 0xe7, 0x57, 0x65, 0x3a, 0xe6, 0xd9, 0xee, 0x94, 0x17,
	0xd2, 0xdf, 0x40, 0x86, 0x26, 0xe8, 0x7d, 0xc1, 0xb6, 0x0c, 0x10, 0x89, 0x32, 0x2d, 0x95, 0xbf,
	0x89, 0x6c, 0x2d, 0xb4, 0x92, 0x84, 0x96, 0xda, 0xb2, 0x24, 0xa1, 0x75, 0x76, 0xd8, 0x7a, 0xac,
	0xb8, 0x9a, 0x97, 0xc4, 0x70, 0x93, 0x34, 0xb5, 0x20, 0xcc, 0x08, 0xc5, 0x24, 0x11, 0xfe, 0x2d,
	0x1c, 0x23, 0x02, 0x34, 0x38, 0x30, 0x1a, 0xdc, 0x26, 0x0d, 0x0c, 0xdd, 0x38, 0xd9, 0x91, 0x4c,
	0xa7, 0x5c, 0x5e, 0xf9, 0x1e, 0x9e, 0xc0, 0x02, 0x0e, 0x76, 0xec, 0xcb, 0x62, 0x36, 0x50, 0x62,
	0x5a, 0xfa, 0x77, 0x28, 0xf6, 0x2a, 0x00, 0x56, 0x8a, 0xc4, 0x94, 0xa7, 0xf9, 0xfe, 0xe5, 0x4c,
	0xc8, 0x14, 0x8f, 0x7c, 0x9b, 0x56, 0x6a, 0xe3, 0xde, 0xcf, 0xd8, 0x1a, 0xfa, 0x79, 0xe9, 0xdf,
	0xdd, 0x59, 0x79, 0xb4, 0xfe, 0xf4, 0x4e, 0x1d, 0x56, 0x55, 0x0c, 0x44, 0x9a, 0x25, 0x78, 0x84,
	0x41, 0xf4, 0x42, 0x28, 0x18, 0x1a, 0xe4, 0x67, 0x05, 0x38, 0x0b, 0x7e, 0x1b, 0x27, 0xd7, 0x54,
	0xf0, 0x53, 0xb6, 0x49, 0x9c, 0x7b, 0x3c, 0xb9, 0x96, 0xf1, 0x23, 0xa6, 0xbc, 0xf0, 0x1c, 0xdc,
	0x03, 0xa4, 0xd7, 0x01, 0x16, 0xcb, 0x71, 0x1d, 0x75, 0x9a, 0x82, 0x88, 0xed, 0x8b, 0x52, 0xc1,
	0x00, 0x45, 0x9e, 0x21, 0x31, 0x96, 0xe5, 0xb8, 0xca, 0xdb, 0x10, 0xcb, 0x44, 0x82, 0xc5, 0x81,
	0x09, 0x87, 0x28, 0x6d, 0x57, 0x74, 0x10, 0xb2, 0xf5, 0x38, 0x3c, 0xa9, 0x74, 0xf9, 0x8a, 0x75,
	0xe1, 0x1b, 0x22, 0x57, 0xe7, 0x18, 0xbf, 0x69, 0x8c, 0x3a, 0xb0, 0xa3, 0x8a, 0x33, 0xf8, 0x35,
	0x63, 0x71, 0x78, 0x62, 0xd4, 0xac, 0xcd, 0xd9, 0xf9, 0x6e, 0x73, 0x3e, 0x61, 0x77, 0xc3, 0xf8,
	0x64, 0x94, 0xf1, 0x2b, 0x21, 0xdf, 0xcc, 0x12, 0xc9, 0x27, 0x22, 0x7e, 0x9f, 0x66, 0x99, 0xce,
	0x30, 0x75, 0x66, 0xd2, 0x54, 0xf0, 0x0d, 0x5a, 0x95, 0x26, 0x40, 0xd8, 0x40, 0x72, 0x1a, 0xf4,
	0x69, 0x2f, 0x37, 0x82, 0x4f, 0x6f, 0x83, 0x75, 0xde, 0xa2, 0x75, 0x9c, 0xa8, 0xf3, 0x16, 0xa8,
	0x63, 0x9d, 0x4b, 0x3a, 0xc7, 0x60, 0xa5, 0x41, 0x19, 0x2b, 0x2e, 0x15, 0x9a, 0xa2, 0x1b, 0x19,
	0x32, 0x78, 0xc1, 0x6e, 0x56, 0x0b, 0xeb, 0x70, 0x5f, 0x5c, 0x3a, 0x60, 0x1b, 0x47, 0x5c, 0x26,
	0xfa, 0xf4, 0x4d, 0xf6, 0x6b, 0x60, 0xc1, 0x47, 0xf4, 0x10, 0x5a, 0x88, 0x74, 0x69, 0xa7, 0x40,
	0x38, 0x2a, 0x18, 0xa8, 0x16, 0x30, 0x24, 0x89, 0xbe, 0xd2, 0x10, 0x7d, 0xd5, 0x88, 0xde, 0xde,
	0xdb, 0x5d, 0xb2, 0xf7, 0x33, 0x76, 0xa7, 0x72, 0x25, 0x52, 0x02, 0x0a, 0x2b, 0xc4, 0x72, 0x4d,
	0x69, 0x41, 0x2c, 0x24, 0xd8, 0x47, 0xdd, 0x5f, 0xc9, 0x84, 0xe7, 0xe9, 0x47, 0x71, 0x24, 0xf8,
	0x14, 0x64, 0x24, 0x15, 0x7e, 0x61, 0x4a, 0x83, 0x26, 0xeb, 0x91, 0xa7, 0x46, 0x7a, 0x4d, 0x06,
	0x7f, 0xeb, 0xb0, 0xad, 0x38, 0x3c, 0x89, 0xc4, 0xb7, 0x73, 0xf0, 0x2f, 0x58, 0x26, 0x60, 0x1b,
	0xe0, 0xb9, 0x74, 0xbe, 0x95, 0x11, 0x1a, 0x98, 0xf6, 0x5c, 0xab, 0x28, 0x18, 0x12, 0x32, 0x5a,
	0x2c, 0xc7, 0xa0, 0x9b, 0xf6, 0x05, 0xf2, 0xec, 0x26, 0x08, 0xfe, 0x1d, 0xcb, 0xf1, 0x4b, 0x71,
	0x21, 0x32, 0xe3, 0xdf, 0x86, 0x86, 0x2c, 0x65, 0xc4, 0x01, 0xf7, 0x27, 0x9b, 0xd9, 0x50, 0xa0,
	0xb0, 0xe6, 0x46, 0xa2, 0x9c, 0x15, 0x79, 0x29, 0x5e, 0xc9, 0xe4, 0xff, 0x91, 0x7b, 0x50, 0xee,
	0x26, 0x52, 0x08, 0x63, 0x08, 0x4d, 0xb6, 0x77, 0x5d, 0x59, 0xdc, 0xf5, 0x1f, 0x2e, 0x63, 0x78,
	0xe8, 0x54, 0x24, 0xff, 0x8b, 0xb7, 0x43, 0x0a, 0x25, 0xbd, 0x68, 0x03, 0x22, 0x40, 0x38, 0x4a,
	0x62, 0x61, 0xff, 0x28, 0xd5, 0xdd, 0x8d, 0x13, 0x35, 0x30, 0x38, 0xf2, 0x90, 0xe7, 0x3a, 0xa4,
	0xb4, 0x59, 0x2c, 0x04, 0x56, 0x1e, 0xe4, 0x13, 0x71, 0xa9, 0x4d, 0x42, 0x04, 0x98, 0x32, 0xe4,
	0x5a, 0x6a, 0x2a, 0x7d, 0x15, 0x0d, 0x85, 0x03, 0xbf, 0xd1, 0xdf, 0x90, 0xe3, 0x06, 0x72, 0xb4,
	0x50, 0xe0, 0xc3, 0xc3, 0x21, 0x44, 0xf0, 0x29, 0x56, 0x41, 0x37, 0x6a, 0xa1, 0x4d, 0xbe, 0x90,
	0x4f, 0x67, 0x58, 0x0d, 0x1b, 0x7c, 0x80, 0x42, 0x73, 0x70, 0x58, 0x84, 0x5c, 0x0a, 0x2c, 0x3e,
	0x83, 0xe9, 0x74, 0x9e, 0x53, 0x65, 0x74, 0xa3, 0xc5, 0x01, 0x6c, 0x52, 0x79, 0xa9, 0xa8, 0xfc,
	0x52, 0x85, 0xac, 0x01, 0xd4, 0xaf, 0x28, 0xb2, 0x49, 0xf1, 0x21, 0xd7, 0xd5, 0xb1, 0xa2, 0x61,
	0xe6, 0xc1, 0x5c, 0xea, 0x99, 0x54, 0x13, 0x6b, 0x00, 0x0b, 0x2f, 0xcf, 0x79, 0x58, 0x94, 0x0a,
	0x8b, 0xa1, 0x1b, 0x55, 0xb4, 0x2e, 0x5b, 0x7c, 0xfc, 0x7e, 0x77, 0xae, 0x8a, 0xdd, 0xb1, 0x4a,
	0x2f, 0x04, 0xd6, 0x43, 0x2a, 0x5b, 0x0d, 0x1c, 0x9c, 0xe6, 0xeb, 0xb4, 0x4c, 0x4f, 0x33, 0x2a,
	0x8b, 0x6e, 0x64, 0xc8, 0xba, 0x64, 0xa1, 0x5f, 0x84, 0xc5, 0x3c, 0x57, 0x58, 0x20, 0xab, 0x92,
	0x55, 0xe3, 0x24, 0xcd, 0x25, 0xb9, 0x86, 0x67, 0xa4, 0x21, 0x1a, 0x82, 0x06, 0x3c, 0x2d, 0x95,
	0x62, 0x42, 0x0c, 0x77, 0x28, 0x68, 0x1a, 0x20, 0x34, 0x46, 0xf8, 0x51, 0xee, 0x09, 0xf5, 0x41,
	0x08, 0xe3, 0x17, 0xa5, 0xae, 0x92, 0xcb, 0x07, 0xc1, 0x46, 0x83, 0x3c, 0x55, 0xb4, 0xee, 0x5d,
	0xba, 0x02, 0x54, 0x40, 0xf0, 0xef, 0x0e, 0xeb, 0xed, 0xcd, 0xcf, 0xce, 0xae, 0xf7, 0xe9, 0x07,
	0x8c, 0x91, 0x3e, 0xe8, 0xbb, 0x94, 0xa7, 0x2d, 0x04, 0x1a, 0x44, 0xcb, 0xab, 0xf1, 0x1b, 0xd7,
	0xe2, 0xc9, 0xe1, 0x7c, 0xaa, 0x3d, 0x59, 0x53, 0xe8, 0x93, 0x74, 0x03, 0x49, 0x8b, 0xdc, 0x8a,
	0xf0, 0x16, 0x0a, 0x01, 0x59, 0x23, 0x6f, 0xd1, 0xb5, 0x9d, 0xc8, 0x86, 0x9a, 0x1c, 0xc7, 0xa6,
	0xb5, 0xb3, 0xa0, 0x26, 0xc7, 0x3b, 0xd3, 0xda, 0x59, 0x50, 0xf0, 0xd7, 0x2e, 0x75, 0xcd, 0xa4,
	0xbf, 0x69, 0x74, 0x3b, 0x56, 0xa3, 0xbb, 0x3c, 0x9e, 0xb7, 0x98, 0x73, 0x30, 0xd2, 0x59, 0xc2,
	0x39, 0x18, 0x01, 0x3d, 0x1c, 0x69, 0x4d, 0x9d, 0xe1, 0x88, 0xaa, 0x82, 0xdb, 0xa8, 0x0a, 0x6b,
	0xa6, 0x2a, 0x50, 0x6d, 0xb9, 0x51, 0xd5, 0x16, 0xfb, 0x6e, 0xd5, 0x6d, 0x5d, 0xf6, 0xb6, 0x99,
	0x3b, 0xe4, 0x97, 0x07, 0x23, 0x1d, 0x68, 0x44, 0x68, 0x74, 0x38, 0xd2, 0x31, 0x45, 0x04, 0x9c,
	0x92, 0xd5, 0x3a, 0xad, 0x53, 0xfe, 0xb0, 0x9a, 0xa6, 0x87, 0x6c, 0x73, 0xc8, 0x2f, 0x2d, 0x96,
	0x0d, 0xf2, 0xb2, 0x06, 0xa8, 0xaf, 0x8c, 0x4a, 0x16, 0x50, 0xeb, 0x36, 0xab, 0x2b, 0x23, 0x01,
	0xb0, 0xc6, 0x6e, 0x9e, 0x4e, 0x0b, 0x55, 0x48, 0xe8, 0x1b, 0x85, 0x0e, 0xac, 0x26, 0x58, 0x17,
	0x2f, 0xf4, 0x0a, 0xea, 0x33, 0x2d, 0x04, 0xc6, 0xfb, 0xa9, 0x34, 0x47, 0x4b, 0xbd, 0xa6, 0x85,
	0x34, 0xc6, 0x8f, 0x75, 0xcb, 0x69, 0x21, 0x60, 0x31, 0x53, 0x4c, 0x4c, 0x2c, 0x19, 0xda, 0x7b,
	0xcc, 0x3c, 0x1d, 0xc1, 0xe3, 0x19, 0x3f, 0x85, 0x2b, 0x45, 0x2a, 0x4a, 0x1d, 0x50, 0x4b, 0x46,
	0x5a, 0x85, 0x76, 0xbb, 0x5d, 0x68, 0xc1, 0x8f, 0x07, 0xe5, 0x10, 0x5a, 0x5f, 0x0a, 0x1e, 0x4d,
	0x51, 0x29, 0xe9, 0x0b, 0xae, 0xce, 0xfd, 0x4f, 0x4c, 0x29, 0x41, 0x92, 0x22, 0xee, 0x42, 0x67,
	0x8c, 0x4f, 0x4d, 0xc4, 0x69, 0x00, 0x7c, 0x0c, 0x33, 0xa7, 0x8f, 0x03, 0xf8, 0xad, 0xf7, 0x48,
	0xcb, 0xd2, 0xff, 0x01, 0x76, 0x38, 0x9a, 0xb2, 0xad, 0x3d, 0xe2, 0xf3, 0x52, 0xf8, 0xf7, 0x9a,
	0xd6, 0x46, 0x10, 0xdb, 0x7a, 0xc8, 0x33, 0xfb, 0x39, 0x87, 0x1d, 0x3f, 0xa3, 0xd2, 0x65, 0x41,
	0xa0, 0x23, 0x74, 0xa9, 0x9a, 0xe1, 0x3e, 0xe9, 0x58, 0x23, 0xe0, 0x9f, 0xef, 0xfc, 0x1f, 0x92,
	0x7f, 0xbe, 0x83, 0x5d, 0x61, 0x7f, 0x29, 0x0b, 0x39, 0x98, 0xf2, 0x44, 0xf8, 0x0f, 0x68, 0xd7,
	0x06, 0xd8, 0xbe, 0x36, 0xfd, 0x68, 0xf1, 0xda, 0x54, 0x59, 0x16, 0xc4, 0xf5, 0x77, 0x6c, 0xcb,
	0x02, 0x62, 0x65, 0x9b, 0x1f, 0x37, 0xb2, 0x4d, 0x95, 0x55, 0x23, 0x71, 0x91, 0x5e, 0x08, 0xf4,
	0xa1, 0x80, 0x2e, 0x8b, 0x6d, 0xdc, 0x7b, 0xc8, 0x9c, 0xb8, 0xef, 0x7f, 0x8e, 0x5d, 0xeb, 0x76,
	0xdd, 0xb5, 0xd6, 0x75, 0x3a, 0x72, 0xe2, 0xbe, 0xf7, 0x39, 0x73, 0xf6, 0xfa, 0xfe, 0xc3, 0x76,
	0x6f, 0x5b, 0x25, 0xbe, 0xc8, 0xd9, 0xeb, 0x7b, 0x5f, 0xb0, 0x95, 0x41, 0xdc, 0xf7, 0x7f, 0x72,
	0xcd, 0x5a, 0xc0, 0x00, 0x29, 0x73, 0x7d, 0x6f, 0x9e, 0x65, 0x42, 0x2d, 0xbf, 0x2d, 0xdb, 0xe1,
	0xec, 0xb4, 0xc2, 0xf9, 0xba, 0x66, 0x11, 0x0f, 0xc1, 0x35, 0x87, 0xb0, 0xcd, 0x5c, 0x0a, 0x30,
	0xaa, 0xe9, 0x44, 0xe0, 0x1d, 0x03, 0x5a, 0xdf, 0xb7, 0x3a, 0xdb, 0x69, 0xaa, 0xc2, 0x8f, 0x75,
	0x8e, 0xd3, 0x54, 0x85, 0xbf, 0xd3, 0xd7, 0x56, 0x4d, 0x81, 0x13, 0xee, 0xe7, 0x93, 0xb7, 0xfa,
	0xb6, 0x8a, 0xdf, 0x1a, 0x3b, 0xd6, 0x15, 0x18, 0xbf, 0x35, 0xf6, 0x4e, 0x17, 0x5e, 0xfc, 0x0e,
	0x8e, 0xd8, 0x16, 0x3d, 0x39, 0x28, 0x31, 0x5d, 0x6e, 0x81, 0xfa, 0x60, 0x9d, 0xc6, 0xc1, 0x5e,
	0xa3, 0x7d, 0xc0, 0x59, 0xef, 0x80, 0x67, 0xc5, 0xf7, 0x68, 0xd2, 0xe0, 0xef, 0x1d, 0x7c, 0xd9,
	0x7a, 0x53, 0x0a, 0xb9, 0x9f, 0x2b, 0x21, 0xe9, 0x41, 0x45, 0x3f, 0xa7, 0x75, 0xea, 0xe7, 0xb4,
	0xc6, 0xa3, 0x99, 0xd3, 0x7e, 0x34, 0xa3, 0x06, 0x37, 0x16, 0xf2, 0x42, 0x48, 0xeb, 0xa1, 0xaa,
	0x09, 0x42, 0x95, 0x83, 0x0b, 0x9b, 0xc5, 0x46, 0xaf, 0x49, 0x2d, 0xd4, 0x7e, 0xce, 0x71, 0x1b,
	0xcf, 0x39, 0xf5, 0xe3, 0xdc, 0x9a, 0xfd, 0x38, 0xf7, 0x97, 0x0e, 0xdb, 0x1c, 0x96, 0x09, 0x75,
	0xb4, 0xd0, 0xea, 0x40, 0x94, 0xc1, 0x6f, 0xe3, 0x9a, 0x6a, 0x21, 0xd0, 0x79, 0x02, 0xb5, 0x9b,
	0x65, 0x5f, 0xf3, 0x6c, 0x6e, 0xfa, 0xde, 0x06, 0x06, 0xd2, 0x02, 0x8d, 0x4d, 0x19, 0x71, 0x51,
	0x65, 0x6b, 0xa1, 0x94, 0xa7, 0x42, 0x99, 0x2a, 0x53, 0xd3, 0x89, 0x02, 0x2d, 0x5e, 0x08, 0xf5,
	0xa2, 0xc8, 0x26, 0x46, 0x0b, 0x4d, 0x06, 0xff, 0x5a, 0x65, 0x3d, 0xb8, 0xad, 0xce, 0x26, 0xfa,
	0x15, 0x31, 0x9c, 0xcb, 0xe7, 0xd2, 0xd4, 0x58, 0xe8, 0x55, 0x35, 0xed, 0x3d, 0x61, 0xdd, 0x43,
	0xf1, 0x01, 0x84, 0x86, 0x7b, 0xf2, 0x92, 0x5b, 0xa8, 0xbe, 0xc2, 0x1a, 0x26, 0x98, 0xf0, 0x2a,
	0x9b, 0xd0, 0x84, 0x95, 0x6b, 0x26, 0x18, 0x26, 0x6a, 0xf1, 0xa7, 0xc5, 0x85, 0xa0, 0x39, 0xab,
	0x78, 0x47, 0xb4, 0x21, 0xef, 0x19, 0x63, 0x87, 0xe2, 0x03, 0x05, 0x77, 0xe9, 0xbb, 0xb8, 0xe8,
	0x5d, 0x3b, 0x5f, 0x54, 0x51, 0x1f, 0x59, 0x8c, 0x30, 0xed, 0x55, 0x36, 0x31, 0xd3, 0xd6, 0xae,
	0x9d, 0x56, 0x33, 0x52, 0xd7, 0x07, 0x9b, 0x9b, 0x99, 0x37, 0x50, 0xa2, 0x26, 0xa8, 0xed, 0x02,
	0xb1, 0x51, 0xfa, 0xdd, 0xb6, 0x9a, 0x55, 0xc8, 0x44, 0x15, 0x93, 0xb6, 0x0b, 0x4d, 0xe8, 0x5d,
	0x33, 0xc1, 0x30, 0xd5, 0x76, 0xa1, 0x39, 0xcc, 0xb6, 0x0b, 0x71, 0xfc, 0x96, 0x6d, 0x1e, 0x8a,
	0x0f, 0x55, 0xd4, 0x97, 0xfe, 0x3a, 0xae, 0x6b, 0x3d, 0x34, 0x34, 0x33, 0x42, 0xd4, 0x64, 0xd7,
	0x19, 0xbd, 0xb8, 0x10, 0xd6, 0x12, 0x1b, 0xb8, 0xcd, 0x02, 0xee, 0xfd, 0x8a, 0xb1, 0xda, 0xbb,
	0xfd, 0x4d, 0xdc, 0xe8, 0xd3, 0x7a, 0xa3, 0x86, 0xf3, 0x47, 0x16, 0x6b, 0xf0, 0xa7, 0x0e, 0x3e,
	0x8c, 0x98, 0x9d, 0x97, 0x36, 0x73, 0xf7, 0x58, 0xf7, 0x65, 0x91, 0xa4, 0xe3, 0xe7, 0x33, 0xf3,
	0x18, 0x53, 0xd1, 0x0d, 0xe7, 0x5c, 0x69, 0x39, 0xe7, 0x03, 0xc6, 0x16, 0x42, 0x99, 0xfd, 0x2f,
	0x61, 0x1c, 0x5c, 0x32, 0x6f, 0xf1, 0xa1, 0x17, 0x1b, 0x53, 0x83, 0x56, 0xc9, 0xc7, 0x86, 0x96,
	0xbe, 0xb9, 0xea, 0xbc, 0xaa, 0x1f, 0xae, 0x75, 0x5e, 0x4d, 0x27, 0x75, 0x8b, 0xba, 0x6a, 0xb5,
	0xa8, 0xc1, 0x1f, 0x3b, 0xf8, 0xc6, 0x83, 0x8f, 0xe6, 0x02, 0x17, 0x0c, 0xeb, 0xa7, 0x04, 0xfc,
	0x5e, 0xf2, 0x57, 0xc2, 0x36, 0x73, 0xf7, 0xa1, 0xc6, 0xeb, 0xac, 0x46, 0x84, 0xf7, 0x1b, 0xc6,
	0x2a, 0xd9, 0x28, 0x70, 0xbe, 0xeb, 0x25, 0xdb, 0xe2, 0x0f, 0xce, 0x98, 0x1f, 0x87, 0xed, 0x27,
	0xf2, 0x48, 0x94, 0xf3, 0x4c, 0x2d, 0x95, 0xaa, 0x65, 0x1c, 0x67, 0xd1, 0x38, 0x4b, 0xa5, 0x3c,
	0x5d, 0x43, 0x81, 0x7e, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x9c, 0x40, 0x24, 0x67,
	0x19, 0x00, 0x00,
}
